### ISSUE TITLE
Hi,me again.....

### ISSUE THREAD

**Issue by Wuxiangdong** [kotelnik/plasma-applet-active-window-control#10]
Hi,I find another bug(though this bug has no influence):There is space when title show "Plasma Desktop"..
another question,Is the word "space" countable? .....

:)

**Comment by kotelnik** [comment]
Hi! Nice to hear from you:) I'm not sure what you mean... Is there a visual space where it shouldn't be? Or some kind of delay?

**Comment by Wuxiangdong** [comment]
There is a visual space where it shouldn't be.
![screenshot_20151006_170148](https://cloud.githubusercontent.com/assets/7942339/10304416/9d9e4200-6c4c-11e5-8f65-601dbe10db9a.png)

So "space" can also mean delay,right?
:)

**Comment by kotelnik** [comment]
Ok, the space on the left? I'll do something about it (add an option or make it smart).

Yes, "space" can also mean a time portion - delay. But it is not that usual usage. :)

**Comment by Wuxiangdong** [comment]
Thank you very much :)

**Comment by kotelnik** [comment]
Sorry it took so long. Please try the latest version :)

**Comment by Wuxiangdong** [comment]
thanks :)

**Comment by Wuxiangdong** [comment]
But it seems strange to add a function just for the situation of "Plasma Desktop"......

**Comment by Wuxiangdong** [comment]
It may make somebody feel does not understand it..

**Comment by kotelnik** [comment]
I'm not sure, I think it is understandable. But maybe I can make the margin automatic based on available height for example? The thinner the panel -> smaller margin. What do you think?

**Comment by Wuxiangdong** [comment]
When I set "Window icon on the right",There is a space when title shows "Plasma Desktop" but there is no space when title shows anything else...
I think the space may be for icons when icons are on left.............
So the bug may be when title shows "Plasma Desktop" and icons aren't on left,A extra space is drawn by mistake

My English is poor,so if you don't understand,you can follow your idea and Don't follow mine..

**Comment by kotelnik** [comment]
No, you're probably right. There shouldn't be any space... I've added there the space before because it looked better in thicker panel. I'll try to do something about it :)

**Comment by Wuxiangdong** [comment]
Thank you very much!!! :)

**Comment by kotelnik** [comment]
Now is the space calculated according widget height. So when it is thin there is no space. When it is thick some margin is added. How do you see this change? Does it look fine? :)

**Comment by Wuxiangdong** [comment]
Yes,It looks finer.Thanks :)

**Comment by kotelnik** [comment]
Good to hear, thanks:)
