### ISSUE TITLE
Don't see application menu

### ISSUE THREAD

**Issue by t0msk** [kotelnik/plasma-applet-active-window-control#106]
Hello, please is application menu working? I am using KDE Neon, and I don't see application menu.

**Comment by fezu54** [comment]
You have to use the version from Github. The version from KDE Store does not include support for Global Menu.

**Comment by kotelnik** [comment]
That's right, thanks fezu. I'll just add that when you use github version (or proper package from distro), you need to remove KDE Store version of the widget so it can work properly.

**Comment by t0msk** [comment]
I have this error, when cmake:

```
CMake Error at CMakeLists.txt:6 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 0.0.11) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/tomsk/awc/build/CMakeFiles/CMakeOutput.log".

```

**Comment by t0msk** [comment]
@kotelnik please can you help me? :/

**Comment by fezu54** [comment]
You need to install the 'extra-cmake-module' package of your distribution to be able to build the applet. I guess you also need to install some qt5-dev and kf5-dev packages as dependencies. 
I don't want to be harsh, but do you think it is a good idea to install a self compiled version from Github if you weren't be able to solve problems like these yourself?

**Comment by kotelnik** [comment]
...but one can also learn :). I should write required packages to README.

Yes, package 'extra-cmake-modules' is required and then probably these, too:
* libqt5-qtbase-devel
* libqt5-qtdeclarative-devel
* plasma-framework-devel

Their names can vary in various distributions. Please tell me what's your distribution and I'll try to advise the proper packages to install.

**Comment by t0msk** [comment]
@fezu54 I dont have any otner option, because I Active Window Control in KDE store is old (app menu is not working), so I want to have the latest version.

@kotelnik I installed **extra-cmake-modules**, but packages **libqt5-*** are not found in repo and **plasma-framework-devel** too. Interesting Because I use KDE Neon and KDE is based on Qt.

**Comment by fezu54** [comment]
It's because the packages are named different in Ubuntu. Try `sudo apt install cmake extra-cmake-modules qtdeclarative5-dev libqt5x11extras5-dev libkf5iconthemes-dev libkf5plasma-dev libkf5windowsystem-dev libkf5declarative-dev libkf5xmlgui-dev libkf5activities-dev build-essential libxcb-util-dev libkf5wayland-dev libkf5archive-dev libkf5notifications-dev libxcb-util0-dev libsm-dev libkf5crash-dev`

**Comment by t0msk** [comment]
@fezu54 thanks, it works :)

But still no menu --> https://i.imgur.com/o2ebpyh.png

**Comment by kotelnik** [comment]
Please make sure that:
* ~/.local/share/plasma/plasmoids/ does not contain _org.kde.activeWindowControl_ directory
* there is only one AWC widget added to your panels
* there is zero Global Menu widgets added to your panels
* System Settings -> Application Style -> Widget Style -> Fine Tuning -> Menubar -> Menubar style is set to Application Menu widget

**Comment by t0msk** [comment]
There is no Menubar style

https://i.imgur.com/c8e9sWK.png

**Comment by kotelnik** [comment]
Oh, I see, you seem to have KDE Neon LTS Edition, is that correct? This contains stable (but also older) packages, that does not support global menu widgets. For that you need e.g. a different flavour of KDE Neon, like the User Edition.

**Comment by t0msk** [comment]
@kotelnik So I switched to another VM, now I have KDE Neon (5.10) User Edition and still nothing.

https://i.imgur.com/c7gQg5p.png

**Comment by kotelnik** [comment]
Just to be sure, hovering the widget with your mouse does not display the menu?

**Comment by t0msk** [comment]
@kotelnik ah great, it works, when hover :)

Thank you very much

**Comment by albertzubkowicz** [comment]
on current KDE Neon it still doesn't work. I'm not using kde-look.org package. Also, the buttons adjustments is a hell of a mess.

**Comment by trmdi** [comment]
@albertzubkowicz
Use applets by psifidotos. This one has been dropped for a long time.

**Comment by yell0w4x** [comment]
With kde plasma 5.12.9 I have same issue, I've checked everything you notified. Looks like menubar style is set automatically for now accordingly to this https://unix.stackexchange.com/questions/429296/in-application-menu-bar-in-kde-plasma-5-12. I have no such an option. 

Unfortunately, the app menu is not shown. First I installed the instance from kde repo, but after read this topic. I uninstalled it and build the one from github. But it doesn't work(

**Comment by trmdi** [comment]
@yell0w4x
Read my comment above.

**Comment by yell0w4x** [comment]
@trmdi Thanx, I tried them before. They worked perfectly for me except one thing due to I refused them. I described it here https://askubuntu.com/questions/1220186/kde5-plasma-move-maximized-window-with-title-hidden-by-grabbing-top-application. Is that somehow possible?

**Comment by trmdi** [comment]
Yes, it possible if you use a Latte panel.

**Comment by yell0w4x** [comment]
Thank you, man

**Comment by yell0w4x** [comment]
You mean https://github.com/KDE/latte-dock?

**Comment by trmdi** [comment]
Yes, the name doesn't say it all. It can be used as a panel.
