### ISSUE TITLE
Suggestion: Menu when hover

### ISSUE THREAD

**Issue by t0msk** [kotelnik/plasma-applet-active-window-control#107]
Hello,

I have a suggestion, that if you hover over window title / aplication name, then it will show a menu. Something like Unity.

Thank you very much

**Comment by Wuxiangdong** [comment]
This is supported,if I don't misunderstand you

**Comment by t0msk** [comment]
Ah, that's great, because I have older version (not from github), I cannot install github version because of errors https://github.com/kotelnik/plasma-applet-active-window-control/issues/106
