### ISSUE TITLE
Application menu and hiding control buttons

### ISSUE THREAD

**Issue by divinae** [kotelnik/plasma-applet-active-window-control#109]
Buttons in default hide on mouse out, but when im using application menu buttons are visible all the time.  
![screenshot_20170918_163221](https://user-images.githubusercontent.com/15931906/30547408-7a873a9a-9c8f-11e7-862b-c89200b7b78c.png)
![screenshot_20170918_163211](https://user-images.githubusercontent.com/15931906/30547411-7c0a40f6-9c8f-11e7-8757-d187f3e69f6a.png)

**Comment by kotelnik** [comment]
Thanks! Now it should be fixed. Please reopen if needed.
