### ISSUE TITLE
Hello...

### ISSUE THREAD

**Issue by Wuxiangdong** [kotelnik/plasma-applet-active-window-control#11]
I think the option "Autofill" would make title looks more natural and nice :)
![screenshot_20151109_185923](https://cloud.githubusercontent.com/assets/7942339/11032243/0a86b720-8715-11e5-9432-8c7fb2db3030.png) (This is the whole panel，some applets can't be seen..)

**Comment by Wuxiangdong** [comment]
Thank you for your work this days:)

**Comment by kotelnik** [comment]
You are kind, thank you. That's a good idea! I'll try to do the "autofill" option. Sorry for my late responses and sorry I haven't done the other thing, yet. I'm a little bit busy right now but I try to look into that next week :)

**Comment by Wuxiangdong** [comment]
Ok,you don't need to rush. :)

**Comment by kotelnik** [comment]
I had some time now so I implemented the autofill feature, please try if it is working for you.

**Comment by Wuxiangdong** [comment]
It works,Thanks :)

**Comment by Wuxiangdong** [comment]
Batman :)

**Comment by kotelnik** [comment]
Thanks :D
