### ISSUE TITLE
Feature request: Unity-like: Show global menu on mouse hover - otherwise: window title

### ISSUE THREAD

**Issue by ChrisP4** [kotelnik/plasma-applet-active-window-control#110]
![screenshot_20171008_215306](https://user-images.githubusercontent.com/14283056/31319884-faf3effe-ac73-11e7-8e45-80700f164dfe.png)
Combine the global menu widget with active window control to have the same functionality as Unity; show the menu on mouse hover: 

but otherwise have the window title: 
![screenshot_20171008_215334](https://user-images.githubusercontent.com/14283056/31319887-0865caae-ac74-11e7-89aa-a065d7966e3b.png)

but the window controls should exist in both cases as shown in the second picture when you have the global menu, you could show only the application icon.

Do you think this is doable?

**Comment by kupiqu** [comment]
Not my configuration but I would say this is already possible

**Comment by ChrisP4** [comment]
@kupiqu really? how so?

**Comment by kotelnik** [comment]
I have this settings for that - see the screenshots:
![screenshot_20171008_231544](https://user-images.githubusercontent.com/1174734/31321024-e48cfb06-ac7e-11e7-98fe-fb8e5a606532.png)
![screenshot_20171008_231606](https://user-images.githubusercontent.com/1174734/31321027-ec9d33a6-ac7e-11e7-90bf-3b2449e35608.png)

**Comment by satishux** [comment]
I don't know if it's only my machine or bug but in Kubuntu 17.10 with both plasma 5.10 and 5.11, active windows control's global menu is broken.

**Comment by ChrisP4** [comment]
@satishux yes for me it's the same. Enabling the settings as seen above does nothing unfortunately.
I'm on debian sid. plasma 5.10

**Comment by Kobtul** [comment]
For me, everything works fine on the KDE Neon 5.11.2. On hover windows title changes to the global menu.

**Comment by ChrisP4** [comment]
Yes, unfortunately I hadn't realized there were two different versions and it wasn't the same if you installed it from the store. Even the settings are the same though don't do anything.

I'm sorry for wasting everyone's time, I installed it from github and now everything's great. KDE Neon as well.

**Comment by FloEdelmann** [comment]
Thanks @ChrisP4, had the same issue and your comment helped fixing it. This should be documented somewhere!

**Comment by ChrisP4** [comment]
@FloEdelmann I'm so happy I saved you some time and yes for sure the build instructions should be in the readme for ubuntu derivatives :)
