### ISSUE TITLE
Readme.md links to Redshift? Is this intentional?

### ISSUE THREAD

**Issue by JaneSmith** [kotelnik/plasma-applet-active-window-control#115]
The Readme.md states the following (in bold):

> PLEASE BE ADVISED, this project is being moved under KDE umbrella (https://phabricator.kde.org/source/plasma-redshift-control/). So please make further translations or pull requests in proper places

Is this intentional? Surely it should link to the Active Window Control's page? I searched for it and found this, which I assume is probably the correct link: https://phabricator.kde.org/source/plasma-active-window-control/

**Comment by kotelnik** [comment]
Thanks for pointing this out! Fixed. :)
