### ISSUE TITLE
AWC randomly changes the space between Application's name and it's menus

### ISSUE THREAD

**Issue by Petross404** [kotelnik/plasma-applet-active-window-control#117]
![screenshot_20180127_181348](https://user-images.githubusercontent.com/18561627/35473888-0169c7f6-038f-11e8-8fb9-d3ee5a8507dd.png)
![screenshot_20180127_181442](https://user-images.githubusercontent.com/18561627/35473889-0190ce96-038f-11e8-97e9-5d51fa52ee73.png)

This happens a lot and not just with konqueror. If I click somewhere else and back to the problematic programm it will re-ajust. Until next time, with another application.

**Comment by kotelnik** [comment]
Thanks! It should now be fixed. Please reopen if you find issues.
