### ISSUE TITLE
Path to Buttons aurorae theme not support ~ and $HOME

### ISSUE THREAD

**Issue by trmdi** [kotelnik/plasma-applet-active-window-control#118]
It can only support: /home/user/path/to/theme/

But not: ~/path/to/theme/
and not:  $HOME/path/to/theme/

**Comment by kotelnik** [comment]
Hi! You are right, thanks for report. I just committed a change that automatically finds proper decoration files based on kwin decoration settings. I also added a context action to manually reload theme if needed (it will not get reloaded after immediate kwin settings change).

Please try it out and reopen this issue if you find problems. Thanks!

**Comment by trmdi** [comment]
Very well. Thanks.

**Comment by trmdi** [comment]
Hey @kotelnik 
I've seen the change, but that's not really good, for example, I'm using `SierraBreeze` window decoration theme (a fork of the Breeze decoration, not an aurorae theme), but I want to use Breezemite (an aurorae theme) as the AWC button theme.

Can you implement a dropdown box which scans the aurorae theme directories, then users can easily select it? Like this:
![image](https://user-images.githubusercontent.com/11857205/35775830-0e4518d8-09c3-11e8-957a-0fe9ab84967e.png)

**Comment by Kishore96in** [comment]
Could you please provide an option to override this? I'm currently using a window decoration that doesn't provide titlebars or titlebar buttons, and I just get empty space where the buttons are supposed to be shown, after this change.

**Comment by kotelnik** [comment]
Sure, sorry about the last change. I naively thought that every aurorae decoration provides the needed files. I'll fix it soon. Please wait :).
