### ISSUE TITLE
Application menu not working with Plasma 5.12

### ISSUE THREAD

**Issue by psifidotos** [kotelnik/plasma-applet-active-window-control#119]
In Plasma 5.12 the mechanism to detect application menus changed. I tried to activate it in AWC but unfortunately it doesnt work...

**Comment by trmdi** [comment]
Maybe you're not using the latest version of AWC.

**Comment by psifidotos** [comment]
> Maybe you're not using the latest version of AWC.

@trmdi I checked it out... the only way to be activated in Latte is to add also a plasma menu plasmoid... are you using Plasma 5.12 and AWC and you see application menus correclty?

**Comment by trmdi** [comment]
Yes, I had the same issue like you. So I tried the git version, and it works.

**Comment by aislanmaia** [comment]
I confirm this issue. What is the release date for the latest version of AWC that works ?

**Comment by trmdi** [comment]
@aislanmaia
Depending on your distro. What one do you use? Though you can use the git version whenever you want.

**Comment by psifidotos** [comment]
> Depending on your distro. What one do you use? Though you can use the git version whenever you 
want.

I use the git version... and afterwards I reported the issue.

I will look into the plasma menu code and see if something changed in order to activate the functionality from plasma. I am aware that in plasma 5.12 the menu detection became automatic, and that is why the option in plasma systemsettings to configure application menu style has been removed. My guess is that only a small activating mechanism may be needed because when I add a plasma menu plasmoid elsewhere then AWC is also showing its menu.

**Comment by psifidotos** [comment]
> I will look into the plasma menu code and see if something changed

Ok, I found it... plasma added a QDbusServiceWatcher in order  to activate I think and this goes also in reverse... When the menu plasmoid is removed or the panel removed or Latte closes then plasma knows it because the connection is lost.. That is how new plasma knows at all times if a menu plasmoid is present... if it isnt even dynamically then it shows the menu in the app normally...

**Comment by trmdi** [comment]
Do you use the github or the cgit.kde version?
I'm mentioning this: https://cgit.kde.org/plasma-active-window-control.git/

**Comment by psifidotos** [comment]
Oh.... I use the github! I didnt know there is one in kde... i will try that one...

**Comment by kotelnik** [comment]
Sorry to be that late to this party :). I have adapted the plasmoid to subscribe / unsubscribe to the appmenu service depending on its settings (Application Menu -> Enable application menu checkbox).  So that should work fine. It is indeed only done in kde repositories. Sorry for your trouble.

The plasmoid is now in review process for addition to official KDE.

**Comment by aislanmaia** [comment]
Nice!!! I think I'll wait for the plasmoid to land officially in repos instead of using the git version. :tada: 

@trmdi I'm using KDE Neon User Edition.
