### ISSUE TITLE
A option for font size.

### ISSUE THREAD

**Issue by Wuxiangdong** [kotelnik/plasma-applet-active-window-control#12]
When I tried increasing the width of the panel,I found that the font looked small.
So I think adding "Font size" could solve this..   : )

**Comment by Wuxiangdong** [comment]
I think it will be useful,for example,if the title just has one line and the width of panel is broad,The text will look small,and somebody(including me) want to make their system-wide font size and this of title different,but there is no way to do that.
So  I think this option could be useful :)

**Comment by kotelnik** [comment]
Fair enough, try the latest commit :)

**Comment by Wuxiangdong** [comment]
Thanks :)

**Comment by Wuxiangdong** [comment]
But,,do you mean let me try? It seems that the last commit doesn't work...

**Comment by kotelnik** [comment]
Thanks for spotting the "Plasma Desktop" issue, I'll repair it.

Well, I just made the font scaling option because it was easier and I thought it will be sufficient. I think most people will only benefit from the size setting and leave the font to be the same as other fonts in their panel so the panel looks consistent. But if you think you'd use a different font, I'll add the option :)

**Comment by Wuxiangdong** [comment]
No,I think it's enough now and font scaling option wooks well,too :)

**Comment by kotelnik** [comment]
Ok :) Now the scaling of "Plasma Desktop" should be fixed, too.

**Comment by Wuxiangdong** [comment]
Thanks :)

**Comment by Wuxiangdong** [comment]
It seems that you didn't update it at AUR,and "plasma5-applets-weather-widget-git" neither

**Comment by kotelnik** [comment]
I know, I was about to do that along with updating kde-apps but I was waiting a while in case you find some problems with the new code. It's now updated.

**Comment by Wuxiangdong** [comment]
OK Thanks :3

**Comment by Wuxiangdong** [comment]
Wait.......
You stay up late?

**Comment by kotelnik** [comment]
Yes, I stayed up very late. As batman I needed to take care of some disturbances in the city... But this is probably off-topic for this bug so I'm closing it here :)

**Comment by Wuxiangdong** [comment]
Thanks batman :D 👍
