### ISSUE TITLE
Buttons get hidden and menu moves when you click on application menu items.

### ISSUE THREAD

**Issue by Kishore96in** [kotelnik/plasma-applet-active-window-control#120]
I am using this plasmoid with the application menu enabled to show on hover, with window control buttons also hidden by default but shown if you mouse over the plasmoid. Recently, there was a slight change in behaviour which seems like a bug. When I move my mouse over the plasmoid, both the buttons and the global menu are shown, which is expected. however, if I click on any of the items in the menu, the buttons get hidden and the menu moves to the left. I then have to make another click to select the intended item.

For the button behaviour, I have enabled:

- buttons next to icon and text
- Dynamic width
- Sliding icon and text

Position of buttons is
- Upper left
- vertical center

For application menu, the enabled settings are 

- fill height
- show next to buttons

I have checked with the plasmoid built from latest git, and the issue still persists.

Edit:
My Plasma version is 5.11.5, and this is on Arch Linux.

**Comment by trmdi** [comment]
Try the git version on AUR.

**Comment by Kishore96in** [comment]
@trmdi Sorry, I forgot to mention in my original report that I am using the git version (https://aur.archlinux.org/packages/plasma5-applets-active-window-control-git/) from the AUR.

**Comment by trmdi** [comment]
Try forcing to reinstall, it might get a newer version.

**Comment by Kishore96in** [comment]
Issue still persists after a rebuild of the package.

**Comment by FloEdelmann** [comment]
I have the same issue using the latest [cgit](https://cgit.kde.org/plasma-active-window-control.git/) version on Plasma 5.12 (KDE Neon).

As a workaround, enabling the "Do not hide on mouse out" option works (of course it is a different user experience, but it stops clickable targets from moving around).

**Comment by kotelnik** [comment]
Hi, thanks for reporting the issue! I've just committed an update (to cgit). It should fix the problem mentioned here.

Just for info: I have also added an option "Do not hide on mouse out" for appmenu. Its behaviour should be on par with the same-named option for buttons.

Please reopen the issue if you find problems. Thanks! :)
