### ISSUE TITLE
Restore custom svg icons option

### ISSUE THREAD

**Issue by ishovkun** [kotelnik/plasma-applet-active-window-control#122]
The AWC version that works with Plasma 5.12 at
https://cgit.kde.org/plasma-active-window-control.git/
killed the option to use custom svg icons. 
I am using my custom non-aurorae (C++) theme (https://github.com/ishovkun/SierraBreeze) which AWC doesn't pick up, and I used to utilize the custom svg option to show similar-style buttons in AWC. Could you please restore the option?

**Comment by trmdi** [comment]
Will you have any updates for SierraBreeze?

**Comment by ishovkun** [comment]
Not planning any for now, why?

On Feb 9, 2018 9:09 AM, "trmdi" <notifications@github.com> wrote:

Will you have any updates for SierraBreeze?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kotelnik/plasma-applet-active-window-control/issues/122#issuecomment-364459919>,
or mute the thread

**Comment by kotelnik** [comment]
Done in cgit :). Please reopen if problems occur.

**Comment by trmdi** [comment]
Works perfectly. Thank you @kotelnik !

**Comment by trmdi** [comment]
@kotelnik 
But it still can not expand `~` and `$HOME` in the path string.

**Comment by kotelnik** [comment]
You are right. I've just pushed a fix for ~. But is it a problem it does not expand env. variables?

**Comment by trmdi** [comment]
Ok, it's not a so big problem. Thank you @kotelnik !
