### ISSUE TITLE
Does not work global menu in KDE Plasma 5.12

### ISSUE THREAD

**Issue by foxlinux** [kotelnik/plasma-applet-active-window-control#123]
Hello!
I noticed that in the new version of cde 5.12, the global menu in your widget does not work.
I really like this widget, but I would like the global menu to work.

**Comment by trmdi** [comment]
You need the latest version on cgit.kde.org.
What distro do you use?

**Comment by foxlinux** [comment]
I use KDE NEON and AntergOS
In kde I installed with git, and in the antergos with aur.
Sorry for my English

**Comment by kotelnik** [comment]
To be sure. On Antergos you should use this AUR package, Is this the one you are using?
https://aur.archlinux.org/packages/plasma5-applets-active-window-control-git/

On KDE Neon, you should use git version from this repository:
https://anongit.kde.org/plasma-active-window-control

Is that what you are using and still get the issue although you are up to date?

**Comment by foxlinux** [comment]
In AntergOS, I'm using just this version
![screenshot_20180211_075923](https://user-images.githubusercontent.com/36325020/36070389-138041c6-0f02-11e8-9486-e13fb398209a.png)
In kde also just tried to establish what you wrote, but it's all useless.
In the new version of KDE 5.12, removed the switch of the widget of the global menu, I think therefore it does not work.
P.S At 5.11, everything works.

**Comment by trmdi** [comment]
@foxlinux 

Try **reinstalling** the AUR version, it could get a newer version from git. You have to be sure that you're using the latest version **8e9fb9009224ce62fcc4ac55ee2d9817b14f851c**

You can check it by the comand: `$ pacman -Qi plasma5-applets-active-window-control-git`

I'm using Plasma 5.12 on openSUSE Tumbleweed. It works perfectly.

**Comment by foxlinux** [comment]
In the antergos, it all worked after reinstalling the widget, and rebooting the system.
Now I do not know how to properly remove and reinstall the widget in kde neon

**Comment by trmdi** [comment]
You can build the latest package from the git source: http://packaging.ubuntu.com/html/packaging-new-software.html#building-the-package

**Comment by wintericie** [comment]
I tried to build the latest git version (8557ce0976b22d9ec701c0e6d30686e12b696247 on https://phabricator.kde.org/source/plasma-active-window-control).

However, the global menu still does not work. I am using Plamsa 5.12.0 installed from kubuntu-backports repository on Kubuntu 17.10.

**Comment by foxlinux** [comment]
After reinstallation, and in kde neon earned. Thanks for the help.

**Comment by wintericie** [comment]
I still cannot open the global menu. I find that when I enable Appmenu in the settings, an error will be printed in .xsession-errors:

file:///usr/share/plasma/plasmoids/org.kde.activeWindowControl/contents/ui/AppMenu.qml:158: Error: Cannot assign QObject* to AppMenuModel*

**Comment by trmdi** [comment]
Can you post your About screen? (press Alt+F2 and type "about") @wintericie

**Comment by kotelnik** [comment]
Can you please also post more from the .xsession-errors log? Thanks!

**Comment by wintericie** [comment]
@trmdi 
![spec](https://user-images.githubusercontent.com/5930472/36188985-b320449e-118a-11e8-9377-6550da7f21a5.png)

**Comment by wintericie** [comment]
I cut out the complete .xsession-errors from adding a new plasmoid into a panel to enabling appmenu. I also marked the positions when I added the new Active Window Control to the panel and enabled appmenu feature with two blocks.
[xsession-errors.txt](https://github.com/kotelnik/plasma-applet-active-window-control/files/1722788/xsession-errors.txt)
