### ISSUE TITLE
Option request for dynamic width

### ISSUE THREAD

**Issue by denzerdhard** [kotelnik/plasma-applet-active-window-control#13]
Can you add an option for this behavior please?
![dynamic_width](https://cloud.githubusercontent.com/assets/3885773/11501996/14971204-985a-11e5-9afc-50cd655b4994.gif)

**Comment by Wuxiangdong** [comment]
I think it could be useful :)

**Comment by kotelnik** [comment]
I'll see what I can do;)

**Comment by Wuxiangdong** [comment]
Hi, @denzerdhard 
I think:

    function dynamicWidthForMaximized() {
        if(currentWindowMaximized) {
            main.Layout.preferredWidth = (Screen.width * horizontalScreenWidthPercent + plasmoid.configuration.widthFineTuning)
        } else {
            main.Layout.preferredWidth = 0.001
        }
    }
should be:

    function dynamicWidthForMaximized() {
        if(canShowButtonsAccordingMaximized) {
            main.Layout.preferredWidth = autoFillWidth ? -1 : (vertical ? parent.width : (Screen.width * horizontalScreenWidthPercent + plasmoid.configuration.widthFineTuning))
        } else {
            main.Layout.preferredWidth = autoFillWidth ? -1 : (vertical ? parent.width : 0.001)
        }
    }

**Comment by Wuxiangdong** [comment]
Please try the latest version :)

**Comment by denzerdhard** [comment]
Works good for me, many thanks.
