### ISSUE TITLE
Will AWC support new GTK menus since Plasma 5.13?

### ISSUE THREAD

**Issue by michaldybczak** [kotelnik/plasma-applet-active-window-control#133]
There is a revolution on horizon and GTK and non-Qt global menus are coming to Plasma 5.13!

http://blog.broulik.de/2018/03/gtk-global-menu/

I don't know how AWC works. If it grabs system global menus or does something on its own but I would like to know if it will work with the GTK and non-Qt menus like described in the post above out of the box or will there be needed some development?

AWC is awesome! Without it global menu experience is severely lacking so I hope AWC will support all global menus on X?

**Comment by michaldybczak** [comment]
It does work! :+1: 
I tested it by installing two packages:

gmenu-dbusmenu-proxy
appmenu-gtk-module

so I didn't have to wait for Plasma 5.13.

**Comment by FloEdelmann** [comment]
@michaldybczak Which distribution are you using?

I'm on KDE Neon User Stable 5.12.3 and I can't see those packages. Looks like I do have to wait until June :pensive: 

Did you have to do something else than just install the packages?

**Comment by michaldybczak** [comment]
I'm using Manjaro KDE.

**appmenu-gtk-module** - is in Manjaro repositories and it seems to be in Ubuntu 18.04 repos as well:

https://launchpad.net/ubuntu/+source/appmenu-gtk-module

**gmenu-dbusmenu-proxy** - is in AUR and for you accessible probably only directly from github:

https://github.com/KDE/plasma-workspace/tree/broulik/gmenu-dbusmenu-proxy/gmenu-dbusmenu-proxy

For me, it was enough to install them and reboot. But for some, it may be needed to edit ~/.xprofile and add:
export GTK_MODULES=appmenu-gtk-module

Few persons said that in one install it works for them, in another it doesn't so I'm not sure what's wrong. gmenu-dbusmenu-proxy is still in beta phase.
