### ISSUE TITLE
Application Menu not working for every app.

### ISSUE THREAD

**Issue by Drakota** [kotelnik/plasma-applet-active-window-control#136]
For some reason, the Application Menu is not working for every app. I tried Firefox and I don't have an app menu, fair enough, but I don't have a menu bar for LibreOffice and VSCode which I find very suspicious. The only app so far that's working is Dolphin. 
I'm using the package  `plasma5-applets-active-window-control-git` from AUR.

**Comment by nerdius** [comment]
It won't work with GTK+, VCL, and some Electron apps and this is an upstream issue (either caused because of the app itself or _libdbusmenu_).
