### ISSUE TITLE
Hide titlebar not working on Plasma 5.13

### ISSUE THREAD

**Issue by nihil21** [kotelnik/plasma-applet-active-window-control#141]
Hi,
I'm running KDE Neon Dev Unstable 5.13, and I noticed that when I check "Hide titlebar" in AWC settings it works only until reboot, and then the titlebar reappears even when maximised.
I'm not sure if it's a problem of AWC or if it's related to Plasma.
Thanks in advance.

**Comment by ishovkun** [comment]
@Void97 Are you sure that you need to comment here? AFAIK the repo moved to Phabricator.

**Comment by nihil21** [comment]
You're right, I didn't notice that. I'm closing this issue then.
