### ISSUE TITLE
[Feature request] add option to increse spacing between window title and menus 

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [kotelnik/plasma-applet-active-window-control#142]
I think this space should be wider
![screenshot_20180630_221326](https://user-images.githubusercontent.com/37955014/42128795-36deb382-7ca3-11e8-8896-46503bc66ff6.png)

**Comment by mazikowski** [comment]
I think what you're looking for is the side margin under the Application Menu tab in the settings.

**Comment by ahmed-h-ayyad** [comment]
yes that's exactly what I looking for
thank you
