### ISSUE TITLE
Not able to install the applet

### ISSUE THREAD

**Issue by Nishit-Dua** [kotelnik/plasma-applet-active-window-control#153]
### how to replicate
i am on a fresh install of kubuntu
i did
sudo bash ./install.sh in plasma>plasmoid folder

Could NOT find XCB (missing: RANDR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindXCB.cmake:187 (find_package_handle_standard_args)
  plugin/CMakeLists.txt:32 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/lemark/.local/share/plasma/plasmoids/plasma-applet-active-window-control/build/CMakeFiles/CMakeOutput.log".

**Comment by trmdi** [comment]
> Could NOT find XCB (missing: RANDR)

You're missing some Build dependencies.
Btw, this applet has no longer received update from the dev for a long time, you should switch to applets by psifidotos.

**Comment by Nishit-Dua** [comment]
> You're missing some Build dependencies.
> Btw, this applet has no longer received update from the dev for a long time, you should switch to applets by psifidotos.

Hey thanks for the information but i somehow got it to work,  knew it wasnt being maintained anymore but i needed it for a particular look.
thanks for the headsup on psifidoto's applets, will check them out :)
