### ISSUE TITLE
good replacement for this?

### ISSUE THREAD

**Issue by mathieujobin** [kotelnik/plasma-applet-active-window-control#154]
even the moved project https://phabricator.kde.org/source/plasma-active-window-control/repository/master/

seems inactive
but now way to ask questions on there. so I am asking here.

I am still using this, on Plasma 5.19 and I love this thing
but I think its the one applet that makes my plasma crash from time to time.
I'm not sure, but its the only one that I have that is unmaintained and does not come with standard distribution.

so I wonder, if there is a good replacement.
or is it easy to troubleshoot ? 

thanks

**Comment by trmdi** [comment]
Use alternatives made by psifidotos: applet-window-{appmenu, title, buttons}
