### ISSUE TITLE
'Hide titlebar for maximized windows' wont be disabled after reboot

### ISSUE THREAD

**Issue by A1ca7raz** [kotelnik/plasma-applet-active-window-control#155]
i turned on the switch and it worked. after i reboot my system, it is disabled and i have to turn on again.

**Comment by trmdi** [comment]
This applet is dead. Use psifidotos' alternatives.

**Comment by arxim-lab** [comment]
> This applet is dead. Use psifidotos' alternatives.

what's that?

**Comment by A1ca7raz** [comment]
> This applet is dead. Use psifidotos' alternatives.

thank you
