### ISSUE TITLE
[Feature Request] Option to always show window buttons

### ISSUE THREAD

**Issue by Leplik500** [kotelnik/plasma-applet-active-window-control#156]
Now, if I minimize all windows on the current desktop, buttons become hidden. But I would like to show buttons even if all windows is minimized. Just for beauty, no functionality

**Comment by trmdi** [comment]
This project has been dropped for a long time. You should try applet-window-buttons instead.

**Comment by Leplik500** [comment]
I tried, but it don't have possibility to be colored by latte

**Comment by trmdi** [comment]
> I tried, but it don't have possibility to be colored by latte

What do you mean?

**Comment by Leplik500** [comment]
Latte can change widgets colors between light and dark versions, but applet-window-buttons doesn't support this feature

**Comment by Leplik500** [comment]
I tried to comment this lines in main.qml, but nothing changed
![image](https://user-images.githubusercontent.com/51443060/134167852-07de3722-6667-42cf-afbf-7476d3319d60.png)

**Comment by Leplik500** [comment]
Ok, I founded a way to color applet-window-buttons with latte
