### ISSUE TITLE
Feature request: show on all desktops

### ISSUE THREAD

**Issue by protist** [kotelnik/plasma-applet-active-window-control#18]
On many "normal" Plasma window titlebars, there is a button that will show that window on all virtual desktops. It's often near the left of the titlebar, and looks like a pushpin (e.g. in Breeze) or dot (e.g. in Oxygen). I find this quite useful, and it would be lovely if Active Window Control could also add this button.

Thank you for the great plasmoid!

**Comment by kotelnik** [comment]
You're right, it would be useful. I'll see what I can do. Thanks for the suggestion :)

**Comment by kotelnik** [comment]
Done, please test :).

**Comment by protist** [comment]
Perfect! Thank you for that! And thank you in general for being a wonderfully responsive dev!

**Comment by kotelnik** [comment]
Thanks for Your positive words. I'm glad You like it:).
