### ISSUE TITLE
Not visible buttons but clicable under text.

### ISSUE THREAD

**Issue by FraQu** [kotelnik/plasma-applet-active-window-control#19]
When option for "Show only when maximized" is enabled there is no buttons visible when active window is not maximized, but unfortunately buttons are still working like they are in visible mode. So, when I click text where the button should be, it works like there would be button (minimizes, maximizes and closes).
Here is preview: https://youtu.be/dtAEHbPxtxw
Sorry for the quality. I don't know why it is like that :(

Anyway, great work! I was looking for this plasmoid for years.

**Comment by kotelnik** [comment]
Thanks for the report, I'll fix it. And thanks for your positive feedback :)

**Comment by kotelnik** [comment]
Should now be fixed, please try. Thanks!

**Comment by kotelnik** [comment]
Closing, please reopen when necessary.
