### ISSUE TITLE
width limit of window title to avoid overlay

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-active-window-control#20]
It would be nice to add an option to limit the width of the window title so it doesn't overlay with the window buttons. 

To be more specific, this would be very useful for extremely long window titles (e.g. browsing webpages with long names). The limit should be adjusted depending on the overall length of the applet, corrected by the length of icon + buttons + separations among them...

Is this easily doable?

Thanks

**Comment by kotelnik** [comment]
Hi! Maybe I understand You wrong but I believe this option is already there:
Settings -> Buttons -> Behaviour: check "Buttons next to icon and text", uncheck "Dynamic width" and uncheck "Sliding icon and text".

By this You avoid overlaying icon and text with window buttons.

**Comment by kupiqu** [comment]
I cannot really test now as I'm in plasma 5.8, but I can try to be clearer, I would like to avoid overly but still would like to have left alignment for text and right alignment for buttons. Would that be possible with the settings you mentioned?

**Comment by kupiqu** [comment]
Oops, I just saw that you fixed the applet for plasma 5.8 already, trying the settings you mentioned...

**Comment by kupiqu** [comment]
It works, indeed. But, what is the purpose of dynamic width and sliding icon and text? I don't see any difference on their status being active or not.

Also the space from text to buttons seem to be too wide, but that is a minor thing :)

**Comment by kupiqu** [comment]
Forget about all the previous message. I had to uninstall and reinstall the plasmoid as it was misbehaving. I will recheck everything again and will let you know...

**Comment by kupiqu** [comment]
Actually, the same happened, I still don't understand what dynamic width and sliding icon and text, perhaps they only do when fill width is not enabled?

**Comment by kotelnik** [comment]
That's right, they are for configurations with "Fill width" disabled. I believe some people use it, but it is certainly not perfect. I should fix some minor issues when using "Dynamic width".

**Comment by kupiqu** [comment]
I see. Anyways, I think this feature request was actually implemented as you said in the first place. I'll close the issue. 
Thanks!
