### ISSUE TITLE
avoid showing buttons for the plasma desktop

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-active-window-control#22]
Similarly to the icon, also buttons should not be shown when no window is on focus (i.e. Plasma Desktop)

**Comment by kotelnik** [comment]
Thanks for reporting! :-) Should now be fixed in git. Please reopen when necessary.

**Comment by kupiqu** [comment]
Actually Plasma Desktop does not appear in my system anymore. The most I get is that the icon of last active app disappears

**Comment by kotelnik** [comment]
Thanks. Please try now.

**Comment by kupiqu** [comment]
It works great now. Thanks!
