### ISSUE TITLE
Broken in plasma 5.7.95

### ISSUE THREAD

**Issue by Wuxiangdong** [kotelnik/plasma-applet-active-window-control#24]
file:///usr/share/plasma/plasmoids/org.kde.activeWindowControl/contents/ui/main.qml:124: TypeError: Cannot call method 'activeTaskId' of undefined

**Comment by kupiqu** [comment]
The applet is stacked in "Plasma Desktop" since Plasma 5.8.0 (I moved from Plasma 5.7.5).

**Comment by kotelnik** [comment]
Thanks for the report and also location of the problem! I need to move to the new API provided by plasma. I'll be working on that this week and release a new version soon.

**Comment by Wuxiangdong** [comment]
Ok,Thanks :)

**Comment by kotelnik** [comment]
Should now be fixed in git :). Please reopen if necessary.
