### ISSUE TITLE
Feature request: Control buttons should follow window decoration scheme

### ISSUE THREAD

**Issue by ishovkun** [kotelnik/plasma-applet-active-window-control#25]
It would be really awesome, if window control buttons followed the current decoration scheme. That would unify the look of the desktop, which the ultimate goal plasma developers are aiming at. But the widget is awesome anyway!

**Comment by kotelnik** [comment]
Thanks for feedback! I've already considered this and made some research and it seems this task is not that easy. Decoration buttons are made in qml (not svg images) and I didn't find any easy way to integrate them in the widget.

Let's keep this issue open. I'll investigate this again later.

**Comment by sollidsnake** [comment]
Instead of following the theme, there could be an option to set manually the icons of the controls. I've used a window control applet in the past that had that option.

**Comment by kotelnik** [comment]
That's a good idea. Since there are (for now) 4 icons (close, maximize, minimize, pin) with 2 or 4 variants (inactive-idle, inactive-hover, active-idle, active-hover). I now use 4 svgz files with 2 or 4 id-named groups. Do you think I should merge them to one file and then offer custom icons by setting this kind of svgz file?

Or what do you think is the right way to set custom icons?

**Comment by sollidsnake** [comment]
I believe you should use the formats that are already used instead of creating a new one with everything inside.
The applet I used in the past offered a dialog box to choose a image for each of the icons. Maybe that would be easier so we don't have to mess with gimp/Inkscape to setup the icons we want.

But I'm not familiar with kde's icon system so I might be speaking nonsense here.

**Comment by vmorenomarin** [comment]
If I change the svgz files on icons/default directory, should change the icons?
I have replaced the the *.svgz files, but still appears the default icons in the widget.

Any suggestion?

**Comment by vmorenomarin** [comment]
After restart kwin, the icons buttons does not appears, but the function of each buttom stay. i.e., if I clic on the position of button, it does his function.

What features mus have the .sgvz files?

**Comment by kotelnik** [comment]
Hi! Sorry I'm answering this late. I will probably (for now) only allow to set custom svgz icons because it would otherwise require i bit more complexity to the code since every button has 2-4 states. I'll add the options soon :).

@vmorenomarin: now to your svgz - it is important to set proper ID to each "subicon" in your svgz file:
active-idle
active-hover
inactive-idle (for 2-state buttons like maximize and pin)
inactive-hover (for 2-state buttons like maximize and pin)

**Comment by vmorenomarin** [comment]
![image](https://cloud.githubusercontent.com/assets/13444664/23581271/ce929258-00de-11e7-9989-8ac87e5ce09e.png)

Here is with your suggestion to the _*.sgvz_ files. Thanks a lot

Theme decoration: [Breezemite](https://store.kde.org/p/1169286/).

**Comment by giogziro95** [comment]
@kotelnik,
> Decoration buttons are made in qml (not svg images)

Colour scheme is a different story, but Aurorae themes actually use SVGZ files. You can check _~/.local/share/aurorae/themes/_ (or _/usr/share/aurorae/themes/_ for system-wide) directory if you have installed one. If you don't, you can install it via _System Settings_ → _Application Style_ → _Window Decorations_ → _Get New Decorations_.

**Comment by michaldybczak** [comment]
Great! I'm happy that something is improving on that area! Been waiting forward to this.

A bit off topic, @vmorenomarin how did you make windows title to work that way with menu like on your screen? When I turn it on it always overlaps on menu so I have to turn it off. No options can fix that, maybe aside one (always fit), but that's causing kwin crashes so I can't use it.

**Comment by giogziro95** [comment]
@michaldybczak Enabling the _Buttons next to icon and text_ option from _Active Window Control Settings_ → _Buttons_ → _Behaviour_.

**Comment by michaldybczak** [comment]
@giogziro95, unfortunately, that doesn't work :(. All I get is the windows title/name behind buttons. Basically, anything in Application Menu doesn't change a thing, no matter what I set, I see no difference. The only option that did work was "always fit", but as I said, it causes plasmashell to crash and it's even hard to undo. It usually looks like that NO MATTER WHAT OPTIONS I CHOOSE when windows name/title is enabled. Actually, options simply doesn't have any visible effect or at least any effect that I could notice. Many options are unclear. For instance, what "elide" is? I couldn't find it in my dictionary :(.

Anyway, I feel that it goes too much off topic and I wouldn't want to hijack this thread. Maybe I start new one. Thanks

**Comment by michaldybczak** [comment]
Update: I uninstalled widget version from manjaro repo and installed the one from AUR and now the options work and title don't overlap with buttons. Still, impossible to set as I want (dynamically, so the buttons position would change according to windows name/title length). This is one of the most complicated widgets to set. I can play with options for an hour and still not get what I want and have no idea if that's even possible.

**Comment by michaldybczak** [comment]
Back to the topic. I wanted to replace default buttons from:

/usr/share/plasma/plasmoids/org.kde.activeWindowControl/contents/icons/default/

to breezmite buttons which are located in: ~/.local/share/aurorae/themes/Breezemite/

I noticed some challenges. First, your widget icons have only two circles, while breezmite icons have 5. Simple extension change from svg to svgz and copying files into widget's default directory does nothing. I deleted additional circle graphics to mimic your original file but that doesn't help. Still old icons are shown. Second, you said we needed to change proper id for each subicon. How do we do that in karbon? Or maybe there is some other program to do it?
If we need to apply those IDs, then there is no actually no need to delete icons just apply proper IDs to some of them?

**Comment by vmorenomarin** [comment]
You must open the svg file as a text file with Kate or other editor. Then you localize the id tags and there you rename this id with the names associated to the buttons of the widget, i. e., active-idle, active-hover, inactive-idle and inactive-hover. Before that, the icons should be in the icons folder of the widget, with the names as show you on the next pic: 

![image](https://cloud.githubusercontent.com/assets/13444664/25666314/d6fd7f1c-2fe5-11e7-9d3b-d731755c4c32.png)

**Comment by michaldybczak** [comment]
What? In kwrite this looks like this:
https://puu.sh/vEr0f/52f53c6616.png
How can I make any head or tail of it?

**Comment by kotelnik** [comment]
Hi! Finally I've made some progress. I don't know, how to properly use current decoration scheme. There is no simple way for built-in decorations (breeze, oxygen, plastik). Aurorae decorations are (as you already showed me) a bunch of svgs, so I've made a support for it. You can now fill in Settings -> Buttons: "Path to aurorae theme" textfield with absolute path to e.g. Breezemite theme (/home/your_username/.local/share/aurorae/themes/Breezemite/). And these will now show up in the widget.

Please let me know if there are some issues :).

**Comment by vmorenomarin** [comment]
I have tried: It's direct to apply a Aurorae theme. Excellent job.

**Comment by michaldybczak** [comment]
Am I going mad? I wrote this commed already two times and I still see nothing here...

Aurorae theme support works fantastic! I'm happy.

I might add that it would be nice to add some tip/info for users who have no idea what aurorae theme is (I didn't know its name till recently myself) and where located.

**Comment by vmorenomarin** [comment]
After a new session, the field "Path to aurorae theme" appears in blank. I must fill the field with path of aurorae theme, every new session.

**Comment by michaldybczak** [comment]
For me it works great since I set it up few days ago. No such issue.

**Comment by giogziro95** [comment]
Doesn't seem to work in my case — the buttons aren't visible on the panel, although they are clickable and perform actions.

- Plasmoid version: 1.7.2
- Aurorae theme: [Arc Dark Transparent](https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/aurorae/themes/Arc-Dark-Transparent)
- Path to aurorae theme: _/usr/share/aurorae/themes/Arc-Dark-Transparent/_

**Comment by giogziro95** [comment]
The workaround that I used to use has also stopped working. The workaround was creating a custom icon set and replacing the default ones with these in _/usr/share/plasma/plasmoids/org.kde.activeWindowControl/contents/icons/_.

**Comment by giogziro95** [comment]
So, Breezemite Aurorae theme works (even though the buttons are huge at full scale), but nothing else I tried does.

Also, here's the custom icon sets I've made: [AWC icons.zip](https://github.com/kotelnik/plasma-applet-active-window-control/files/990960/AWC.icons.zip).

**Comment by kotelnik** [comment]
> it would be nice to add some tip/info for users who have no idea what aurorae theme is
Good point. But I intend to make a C++ plugin code for determining the decoration automatically. So this state is hopefully a temporary solution.
> After a new session, the field "Path to aurorae theme" appears in blank
I cannot replicate that, sorry. New session means, you log out and log in?

@giogziro95: I've now added a combo box to settings where you can choose between svg and svgz images for aurorae theme. Try the svgz. It is what Arc theme uses.

**Comment by vmorenomarin** [comment]
> I cannot replicate that, sorry. New session means, you log out and log in?

After a new boot. I dont know if occurs the same in log out and log in.

**Comment by giogziro95** [comment]
@kotelnik Oh, great. Thank's for implementing that.

Now the only problem is the sizing and margins — I can't make them match to the Aurorae theme. I can't make the buttons 100% of the size of decoration buttons and anti-aliasing causes it to look worse than that. Also, margins don't really match up.

Screenshot:
![AWC buttons](https://cloud.githubusercontent.com/assets/2781117/25948369/317c79b4-3664-11e7-92cd-fc67e0a43d78.png)

**Comment by giogziro95** [comment]
> After a new session, the field "Path to aurorae theme" appears in blank.

That's not the case on my desktop, but what happens, is it switches back to _.svg_ from _.svgz_.

**Comment by vmorenomarin** [comment]
> After a new session, the field "Path to aurorae theme" appears in blank.
Solved. Thanks!!!
