### ISSUE TITLE
Don't work with Plasma 5.8

### ISSUE THREAD

**Issue by Maboroshy** [kotelnik/plasma-applet-active-window-control#27]
Widget buttons stopped working after update to Plasma 5.8. They must have changed some commands widget use to control windows.

**Comment by phantom-code** [comment]
And window title is painted over the buttons

**Comment by kotelnik** [comment]
I cannot replicate it on my updated Arch using Plasma 5.8.2, KF 5.27. What is your widget configuration? How did you install the widget?

**Comment by Maboroshy** [comment]
Looks like I had some outdated version installed from KDE store. Installed the git version form AUR and everything is working. Sorry I wasted your time. I'm addicted to your widget and working without it was painful. :smile:

**Comment by kotelnik** [comment]
I really like that somebody is "addicted" to my widget :).

I should update the KDE store version, I didn't logged in there for some time...
