### ISSUE TITLE
Always focused on "Plasma Desktop"

### ISSUE THREAD

**Issue by colinkeenan** [kotelnik/plasma-applet-active-window-control#28]
I'm running up to date Arch Linux with `plasma-desktop 5.8.4-1`. I don't know how to check the version of this applet that I'm running. It was working great until about a month ago. Since then, it always shows the title of the active window to be "Plasma Desktop". So, the only thing I can do with it is "Left click to present windows (All Desktops)". I am not able to control the actually active window with it.

**Comment by kotelnik** [comment]
Hi, thanks for reporting! Please try latest git version. You can use AUR package plasma5-applets-active-window-control-git (maybe you're already using it). You can check the version of applet by accessing it's settings. It is placed in the top right corner of Appearance settings dialog.

**Comment by colinkeenan** [comment]
I was not using plasma5-applets-active-window-control-git. I was just using the "Active Window Control" widget that comes with Plasma 5. However, I do not understand how to check the version. Under Appearance in the Settings dialogue, I just see:  Workspace Theme, Color, Font, Icons, Application Style. I had checked into each of these before, and didn't find Plasma Window Control (or any other widgets). Of course, you probably mean it shows up in the  "Active Window Controls Settings - Plasma: Appearance" dialogue. But, there is nothing about the version on this dialogue. Even after installing plasma5-applets-active-window-control-git.

Just now, I downloaded, built, and installed plasma5-applets-active-window-control-git. Nothing changed. I reboot. Nothing changed. I removed the "Active Window Control" widget from my panel and then put it back on. Nothing changed.

**Comment by kotelnik** [comment]
Sorry for my late responses. The only thing I could think of right now is checking that directory ~/.local/share/plasma/plasmoids/ doesn't contain folder "org.kde.activeWindowControl". And if it does, remove it. So you'll end up with only one installation of this widget.

**Comment by colinkeenan** [comment]
Thanks. That fixed it.
