### ISSUE TITLE
Feature request: Re-order buttons

### ISSUE THREAD

**Issue by MattMcHackit** [kotelnik/plasma-applet-active-window-control#29]
I love think widget! :-) 99% perfect! Can I make a feature request, please? Might it be possible to add a setting so you can re-order the buttons? I'd rather have them in this order: Close - Minimize - Maximize/Restore.

Different users may order the buttons differently, so it could become confusing if the widget buttons do not match.

Thank you!

**Comment by MattMcHackit** [comment]
Yay! Feature present in version 1.6.1! Works well, thank you so much!

**Comment by kotelnik** [comment]
Thanks for suggestion and feedback and sorry for my late responses :).
