### ISSUE TITLE
"present windows" feature request

### ISSUE THREAD

**Issue by joseffilzmaier** [kotelnik/plasma-applet-active-window-control#3]
Just installed this through the AUR and I love this already. This lets me recreate my plasma workflow in Plasma 5! Thank you!

One feature request though:
I'd love to be able to activate the "present windows" desktop effect by clicking on the title. (Preferably with option to show only windows of the current virtual desktop)

Thanks!

**Comment by kotelnik** [comment]
I'm glad you like it. I'll try to implement it.

**Comment by kotelnik** [comment]
That took a while right? Try it and report problems ;-) Thanks!

**Comment by joseffilzmaier** [comment]
Thank you *very* much! I'm trying it right now and it recreates my old workflow perfectly. This is awesome! I'll report problems if i find some, but so far this is looking great!

Thanks!

**Comment by kotelnik** [comment]
I'm glad to hear that. So I'm closing this issue...
