### ISSUE TITLE
Feature request: 2 separated applets 

### ISSUE THREAD

**Issue by divinae** [kotelnik/plasma-applet-active-window-control#31]
Can u make 2 separated applets like xfce Windowck Plugins.

http://goodies.xfce.org/projects/panel-plugins/xfce4-windowck-plugin

I mean, when i'm have no bar when maximized window i want to see window title in center of plasma panel , and window buttons in right edge.

**Comment by MattMcHackit** [comment]
Couldn't you do this by having two instances of the widget configured differently?

**Comment by kotelnik** [comment]
Yes, this should be possible with every Plasma widget. In fact, I've just tried that, it works. But please reopen if it is not what you meant.
