### ISSUE TITLE
Feature request: Set font independently of system font

### ISSUE THREAD

**Issue by MattMcHackit** [kotelnik/plasma-applet-active-window-control#34]
Would be cool if you could set the font independently of the system fonts so, for example, the text could be bold to differentiate it from neighbouring apps like the global menu.

Thank you :-)

**Comment by blanelegant** [comment]
I actually submitted a pull request implementing this feature (well, the 'bold' part) the day before you posted this request! See pull request #32

**Comment by MattMcHackit** [comment]
Oh! Thank you!

**Comment by kotelnik** [comment]
Thanks again Blane! I'll do the font part :)

**Comment by MattMcHackit** [comment]
I badly need to learn to code properly lol :-P

**Comment by kotelnik** [comment]
:) OK, done. Please reopen if problems arise.
