### ISSUE TITLE
reverse title order, first app then specifics

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-active-window-control#37]
please check the attached patch

I'm using it by default, I find it useful. This could be set as an option for the final user if you would like...

[reverseTitleOrder.patch.txt](https://github.com/kotelnik/plasma-applet-active-window-control/files/769409/reverseTitleOrder.patch.txt)

**Comment by kotelnik** [comment]
Added by supporting custom regex replacing :).

**Comment by kupiqu** [comment]
Cool approach! :)

However, for Chromium (and perhaps Chrome), it doesn't seem to work fine, is it?

**Comment by kotelnik** [comment]
You're right! Sorry, here:
`^(.*)\s*[—–\-:]\s*(Mozilla )?([^—–\-:]+)$`
...I'll update the default. Thanks!

**Comment by kupiqu** [comment]
perfect, thanks!

**Comment by kupiqu** [comment]
The regular expression above seems to fail in Mozilla Firefox when there is no dash (it shows just "Mozilla Firefox", and I would like to be replaced to just "Firefox").
This happens transiently at startup for all websites until they are load, and it is persistent for an empty tab, at least until switching tabs).
I think this could be fixed by just removing all appearances of "Mozilla " from the window title, irrespective of whether a dash is present or not.
Could this be added to the regular expression? Thank you!
