### ISSUE TITLE
increase resolution of font scaling

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-active-window-control#38]
I found it useful to scale the font size by 0.95, so increasing the resolution would perhaps be also useful for others.

Please see attached patch

[higherResolutionFontScaling.patch.txt](https://github.com/kotelnik/plasma-applet-active-window-control/files/769412/higherResolutionFontScaling.patch.txt)

**Comment by kotelnik** [comment]
Added, thanks! :)
