### ISSUE TITLE
"Plasma Desktop" will appear in a applet that set not to show window title

### ISSUE THREAD

**Issue by Wuxiangdong** [kotelnik/plasma-applet-active-window-control#4]
Hi,I have used this wonderful applet for a while.It's a great applet!But the word "Plasma Desktop" will appear in a applet that set not to show window title.Could you fix it up?

Thanks

(sorry for my bad English)

**Comment by kotelnik** [comment]
This one was easy. Thanks for feedback and reporting :)

**Comment by Wuxiangdong** [comment]
Thanks :)
