### ISSUE TITLE
Appmenu shouln't be visible when no window is on focus

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-active-window-control#46]
This applies when app menu appears next to icon and text (other cases I think are ok).

It can be fixed by adding `&& !noWindowVisible` to (line 23 in AppMenu.qml):

`visible: appmenuEnabledAndNonEmpty && (appmenuNextToIconAndText || mouseHover || appmenuOpened)`

**Comment by kotelnik** [comment]
Thanks! It should now be fixed, please reopen if problem occurs.
