### ISSUE TITLE
Option to hide window title when it's "Plasma desktop"

### ISSUE THREAD

**Issue by Niklas81** [kotelnik/plasma-applet-active-window-control#48]
Like the title say, could we please have the opt-in option to display nothing when the title it "Plasma desktop". I find it rather annoying.. :)

**Comment by bkrith** [comment]
Hi @Niklas81 I just added it in my testing fork. You can find the code and the files in my pull request. It's open and waiting the approve from @kotelnik . 
Sorry for my english

**Comment by Niklas81** [comment]
Awesome, thanx!

**Comment by kotelnik** [comment]
The 'Plasma Desktop' text is now configurable along with optional no-window icon.

**Comment by MattMcHackit** [comment]
Does the latest revision include @bkrith 's changes, please?

**Comment by kotelnik** [comment]
You mean these? https://github.com/kotelnik/plasma-applet-active-window-control/pull/47
I think so. Are you missing some of them?

**Comment by bkrith** [comment]
@kotelnik make it more sophisticated and elegant! more efficient! ;D

**Comment by MattMcHackit** [comment]
Working perfectly now! Great job! :-)

**Comment by kotelnik** [comment]
Thanks :)
