### ISSUE TITLE
Plasmoid not updated

### ISSUE THREAD

**Issue by bkrith** [kotelnik/plasma-applet-active-window-control#49]
Hi, and sorry again!
It works but not trigger the activeWindowModel for update. You must unfocus/focus the window to change the plasmoid content. For some reason the tasks not updated...

I added a listview to update the model...

ListView {
        model: activeWindowModel
        delegate: Item {}
}

Maybe problem is with my versions - settings but older versions works! Dont try to fix it if no one else has the same problem!

**Comment by kotelnik** [comment]
Hi! I believe I've fixed that in the latest commit: https://github.com/kotelnik/plasma-applet-active-window-control/commit/277bc315c1ca314f6f354d13fbaa00b8436f4479

Please try if it works for you.
