### ISSUE TITLE
Window title and icons mixed up

### ISSUE THREAD

**Issue by strepon** [kotelnik/plasma-applet-active-window-control#5]
Nice work, thanks! I appreciate that there is such an applet for KDE5.
However, the icons get mixed up with the title if they're set to the left and always visible:
![window_control](https://cloud.githubusercontent.com/assets/9050387/8637968/1f64a198-28ab-11e5-8905-569a2bc6f0cf.png)
Can this be fixed or is it an issue of my settings?

**Comment by Wuxiangdong** [comment]
You can put two,one shows title and the others shows buttons
sorry,my English is poor so I can't write more.

**Comment by strepon** [comment]
Yes, that works - thanks for the tip, really useful!

**Comment by kotelnik** [comment]
Hi, thanks for resolving this without me :)) Maybe there is such functionality missing - I mean to push aside icon and text by the full sized window buttons. I will probably implement it when I have more time. Thanks for feedback and report :)

**Comment by kotelnik** [comment]
Hello, I commited an option to allow window buttons next to icon and title. If you are still interested :)

**Comment by strepon** [comment]
It works as expected. Thanks a lot:))
