### ISSUE TITLE
slidingIconAndText does not work for Plasma Desktop

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-active-window-control#51]
There is a gap in space when windowTitleText.text = plasmoid.configuration.noWindowText (which by default corresponds to Plasma Desktop). The gap relates to the space that is occupied by window buttons.

However, buttons are not present when no window is active, and, accordingly, the space that buttons occupy should be taken out as well.

I tried enabling/disabling slidingIconAndText and Dynamic width, with no change.

By the way, wondering if a better default for plasmoid.configuration.noWindowText would be Plasmashell

**Comment by kotelnik** [comment]
Thanks for report! It should now be fixed.

About the better default I'm not so sure. "Plasma Desktop" was proposed to me by another user in the past and I kind of like it more :). And now that it can be changed to whatever anybody wants... the default matters even less IMHO :).
