### ISSUE TITLE
At plasma launch no window appears as active (whether or not that is the case)

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-active-window-control#54]
Please check if this is happening to you as it happens to me:

1. give focus to some app and restart plasma:
2. `kquitapp plasmashell`
3. `kstart plasmashell`

It is expected that the applet reflects the active window even at plasma launch, but what I get is just the behavior when no active window is active. I need to move to a different window and come back to get the menu of the first.

**Comment by kotelnik** [comment]
Thanks! This should now be fixed.

**Comment by kupiqu** [comment]
Excellent!
