### ISSUE TITLE
KDE Store version doesn't work

### ISSUE THREAD

**Issue by michaldybczak** [kotelnik/plasma-applet-active-window-control#58]
Plasma 5.8.2
Manjaro KDE
Kernel 4.10

All I get is "Plasma Desktop" on a panel. Size of a widget and stripping of titlebar when maximized works, but there are no icons showed. I can change most options as I want and see no effect after applying. The only way to access buttons is right-click and they don't even work. So basically aside stripping of a title bar (which does so much better then the script), the widget is useless.

It seems like a perfect widget to combine with global menus, but it doesn't work correctly.

Is there any way to debug it?

**Comment by michaldybczak** [comment]
Problem fixed. It turned out that the kde store version is just trash and doesn't work. When I got rid of it and installed widget from repo, it started to work as intended and showed much more options.

However new problem emerged.... Widget crashes plasmashell process constantly. Every second mouse click doesn't work and result in black screen and no panels, so I have to reload plasmashell. Getting rid of the widget stopped plasmashell crashes.

So in the end so or so, applet doesn't work :(.

**Comment by michaldybczak** [comment]
It looks like my current plasmashell issue was already posted here:

https://github.com/kotelnik/plasma-applet-active-window-control/issues/26

When I changed window title to default just elide, crashes stopped. I was able to fit the widget to my needs very well after all.

Please, close this issue.

**Comment by kotelnik** [comment]
It is weird, that the KDE Store version doesn't work. I did update it recently, it should work. However by installing the widget through a regular package you gain the AppMenu functionality which is otherwise unaccessible.

**Comment by michaldybczak** [comment]
Well, installing from store went well at first glance but then nothing worked as supposed. I thought that maybe some settings or bugs on my account are in place so I switched to test user and... I couldn't even download widget from the store. I was always getting "file couldn't be found".

Maybe this was some temporal kde store server failure which resulted in file corruptions or whatnot? Anyway, repo version is awesome and works as I wanted (kinda in unity way). It took me a while till I found some right settings but now I'm pleased with the effect. Maximized window is stripped of title bar and buttons appear on the left side of panel, next to global menu. 

What I miss is the ability to drag the window down from bar to a un-maximized mode. It worked without your widget. Also it would be great to have a window icon menu in icon that is showing, just like on normal title bar, so I could have access to advances settings (like switching to virtual desktops). At the moment maximized window with stripped title bar has a bit thinner functionality without that, but in overall it's great. I can always access it on right-click from icon task manager.

Now when global menu is available, your widget should be a default package on plasma installs, because without it, global menu alone has not enough functionality.

In the future it could be nice if windows button would be dependent on the chosen title bar theme. At the moment they fit nicely to default plasma styles which works for me, however if I wanted to have more "mac-isch" buttons... Just a thought :).

Anyway, good job!

**Comment by michaldybczak** [comment]
Ach, I just recalled! Some plasma review mentioned, that widgets downloaded from store function are broken, this is a known bug and they are working on it. So that's not your widget after all.

Totally forgot about it. That was my first widget installed (default ones were enough for me till now) so I was not aware of it and only heard it was bugged.
