### ISSUE TITLE
Regression: control buttons are invisible

### ISSUE THREAD

**Issue by protist** [kotelnik/plasma-applet-active-window-control#6]
Hi, love the plasmoid! However, a recent update (perhaps in the last two recent commits?) has made the control buttons invisible. I can still click where they should be and they work as expected, but cannot see them. See the red arrow in the following screenshot.

![Invisible control buttons](https://i.imgur.com/B3HRTlu.png)

I built some older commits, and this regression was introduced in commit 2e9ad233fcc5220ac0f9396c81db23af37f012d0. The version previous to this works fine. This bug occurs whether I have "Sliding icon and text" selected or not. 

Arch Linux
Plasma 5.3.2

**Comment by kotelnik** [comment]
Hi! Thanks for reporting! You probably use non-breeze theme, right? I didn't tested my plasmoid with another theme but I could replicate this bug with Air or Oxygen desktop theme. Now it should be fixed, please try the latest commit :)

**Comment by protist** [comment]
I actually thought that I was using Breeze, but I've always been a little confused by the different components that can be configured. In System Settings, I have:
* `Workspace Theme` > `Look And Feel` > `Breeze`
* `Workspace Theme` > `Desktop Theme` > `(Customised)`, but it's all Breeze except for an opaque `Panel Background`.
* `Application Style` > `Widget Style` > `Applications` > `Widget style` > `Breeze`
* `Application Style` > `Window Decorations` > `org.kde.breeze`

In any case, the latest commit works excellently. If you are still interested, I'm happy to work out exactly what theme I'm using and/or troubleshoot more.

Thanks for the quick fix. Cheers.

**Comment by kotelnik** [comment]
The customized desktop theme explains it, it probably present itself under different name. I'm glad it worked :)
