### ISSUE TITLE
Switching - a new feature - guess 

### ISSUE THREAD

**Issue by Jacobtey** [kotelnik/plasma-applet-active-window-control#60]
Hi!
First, thank you for your amazing applet.
Well, recently it has become a new app-menu feature. So, I guess it would be not bad to add a possibility between app-menu & window title by mouse wheel to switch on the fly.
What do you think bout this?

**Comment by kotelnik** [comment]
Hi! Thanks for your positive words :).

Do you mean that window title OR menu would be always visible and this state would be switched by mouse wheel? Personally I find more useful that window title is always visible while menu gets visible only on mouse-over (you don't need it until then). This can be achieved by checking:
- Fill height
- Show next to buttons
...these settings only in widget's Application Menu settings.

But maybe I misunderstood your intentions?

**Comment by Jacobtey** [comment]
> Personally I find more useful that window title is always visible while menu gets visible only on 
mouse-over

Yeah. It's more better. I've found this feature later.
