### ISSUE TITLE
Bad spacing in the application menu

### ISSUE THREAD

**Issue by giogziro95** [kotelnik/plasma-applet-active-window-control#61]
The menu text in not in the middle of the panel like the title bar text is. They also have different font sizes and thus, heights.

**Version:** 1.7.1.

**Screenshot:**
![AWC](https://cloud.githubusercontent.com/assets/2781117/23824012/25ca6b8c-0688-11e7-8b23-9e7fd9ff858b.png)

**Comment by fkrz** [comment]
To center vertically, you may want to check the "Fill Height" box in the Active Window Control Settings > Application Menu.

For the different font size, can confirm : 
![screenshot_20170325_121515](https://cloud.githubusercontent.com/assets/26671073/24321803/b4907bae-1155-11e7-8705-4ba5c4f780bb.png)

**Comment by giogziro95** [comment]
@fkrz I have it checked. When I uncheck it, the menu bar is on the top side, when I check it, it's on the bottom side. When checked, it appears to be slightly more centred, though. My panel height is 26 px, DPI is 96.

**Comment by giogziro95** [comment]
The bug has disappeared recently, but the Plasmoid version is still 1.7.1. I don't know if it had something to do with the panel itself.

![menubar](https://cloud.githubusercontent.com/assets/2781117/24453028/3caa337e-1497-11e7-9ac1-3d97cff3cfad.png)

**Comment by fkrz** [comment]
That's interesting ; nothing changed for me. Have you modified anything to get it working ? Re-building the widget from GitHub maybe ?

**Comment by giogziro95** [comment]
No... I'm using [this package](https://aur.archlinux.org/packages/plasma5-applets-active-window-control-git/) and it reads:

> Last Updated:	2017-02-15 22:18

It might be an upstream issue.

**Comment by kotelnik** [comment]
Hi! The package is using github master branch directly, so that's not the case.

It is weird that the text in buttons is lower then window title text. I cannot replicate that (using the same package). Please try latest version (I've just updated the package version).

If the problem persists, try playing with widget settings -> Application Menu -> "Menu button text size scale".

**Comment by kotelnik** [comment]
Oh, I misunderstood the comments, fkrz has still the problem, right? In any case please try the latest version and if problem persists, please tell me your distro / Qt version, Plasma version, KF5 version :). Thanks!

**Comment by fkrz** [comment]
Well, I still had the problem so I stopped using the Application menu function. I just upgraded (from source), and now the menu just won't show up, so... I guess even I can't replicate !

Running Manjaro with : 
- KDE Plasma version : 5.9.4
- KF5 version : 5.32.0
- Qt version : 5.8.0

Thanks :)

**Comment by kotelnik** [comment]
It gets weirder right?:) But it is good we both have arch based distro, so we will figure it out. Please check that you have only one Active Window Control widget added in desktop / panel and that there is no other widget showing global menu. Also check that you don't have store.kde.org version of this widget installed in ~/.local/share/plasma/plasmoids/ folder. If I understand it right, you installed this widget by standard "sudo make install". This should be good enough. Also note, that global menu is supported only by qt applications.

But you probably know all that. If nothing got better, please try again with clean plasma config (e.g. by temporarily renaming ~/.config/plasma-org.kde.plasma.desktop-appletsrc file and restarting plasma). The widget can be "invisibly" added somewhere in panel and stealing global menu to the visible one.

Also note that manjaro users can install AUR packages like the one mentioned by giogziro95. There is also plasma5-applets-active-window-control package in stable (community) repo, not sure if this is also available in manjaro.

**Comment by fkrz** [comment]
Thanks for the quick answer ! Unfortunately nothing did the trick - still can't see the menu (in Qt apps of course :) )

I used to have the AUR package, and just uninstalled it to try the git version directly when I saw your message earlier.

It's really weird that it didn't work with a fresh plasma though - just to be safe, I tried inserting the native Global Menu widget afterwards, and it worked fine :/

**Comment by kotelnik** [comment]
One more stupid question: the app menu is enabled in widget config, right? (Sorry, I'm trying to rule out every scenario I can think of).

Please restart plasma in terminal:
```
$ killall plasmashell
$ plasmashell &
```
Then switch applications and make sure one of the activated app is a qt5 one. And send me the console log, please. Maybe I can read something from it.

**Comment by giogziro95** [comment]
No such issues here on 1.7.2 as well.

**Comment by fkrz** [comment]
Hi, sorry for the late answer. Still not working though. Here is the output at launching plasmashell : 

`Icon theme "elementary" not found.
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
No metadata file in the package, expected it at: "/home/florian/Pictures/Wallpapers/"
No metadata file in the package, expected it at: "/home/florian/Pictures/Wallpapers/"
No metadata file in the package, expected it at: "/home/florian/Pictures/Wallpapers/"
qml: initializing appMenuModel...
qml: appMenuModel failed to initialize: Error: Qt.createQmlObject(): failed to create object: 
    file:///usr/share/plasma/plasmoids/org.kde.activeWindowControl/contents/ui/inline:1:89: module "org.kde.private.activeWindowControl" is not installed
qml: initializing appmenu...DONE null
file:///usr/share/plasma/plasmoids/org.kde.activeWindowControl/contents/ui/AppMenu.qml:49:9: QML Connections: Cannot assign to non-existent property "onRequestActivateIndex"
Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
qml: onLoaded
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
Both point size and pixel size set. Using pixel size.
file:///usr/share/plasma/plasmoids/org.kde.activeWindowControl/contents/ui/main.qml:242:13: QML Text: Binding loop detected for property "computedWidth"
file:///usr/lib/qt/qml/QtQuick/Controls/ScrollView.qml:350: TypeError: Cannot read property 'padding' of null
file:///usr/lib/qt/qml/QtQuick/Controls/ScrollView.qml:351: TypeError: Cannot read property 'padding' of null
file:///usr/lib/qt/qml/QtQuick/Controls/ScrollView.qml:352: TypeError: Cannot read property 'padding' of null
file:///usr/lib/qt/qml/QtQuick/Controls/ScrollView.qml:353: TypeError: Cannot read property 'padding' of null
file:///usr/lib/qt/qml/QtQuick/Controls/Button.qml:99: TypeError: Cannot read property of null
The image "widgets/button" doesn't contain any of the prefixes ("shadow")
The image "widgets/button" doesn't contain any of the prefixes ("shadow")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
kf5.kcoreaddons.desktopparser: Could not locate service type file kservicetypes5/plasma-popupapplet.desktop, tried ("/home/florian/.local/share", "/usr/share", "/usr/local/share")
Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
Notifications service registered
The image "widgets/button" doesn't contain any of the prefixes ("shadow")
The image "widgets/button" doesn't contain any of the prefixes ("shadow")
The image "widgets/button" doesn't contain any of the prefixes ("shadow")
libkcups: Create-Printer-Subscriptions last error: 0 successful-ok
libkcups: Get-Jobs last error: 0 successful-ok
libkcups: Get-Jobs last error: 0 successful-ok
Trying to use rootObject before initialization is completed, whilst using setInitializationDelayed. Forcing completion
qml: disabling redshift
qml: renderModeString: 
qml: disabling redshift
The image "widgets/button" doesn't contain any of the prefixes ("shadow")
Plasma Shell startup completed
libkcups: 0
libkcups: 0
Both point size and pixel size set. Using pixel size.
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
networkmanager-qt: void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "AllDevices"
networkmanager-qt: void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "Capabilities"
networkmanager-qt: void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "Devices"
networkmanager-qt: void NetworkManager::NetworkManagerPrivate::propertiesChanged(const QVariantMap&) Unhandled property "GlobalDnsConfiguration"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "LldpNeighbors"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "Real"
networkmanager-qt: virtual void NetworkManager::DevicePrivate::propertyChanged(const QString&, const QVariant&) Unhandled property "S390Subchannels"
qml: clearing connected sources, stop source was: killall redshift; redshift -x
qml: enabling redshift with command: redshift -l 50:7 -t 6500:4000 -b 1:1 -g 1:1:1 -r
file:///usr/share/plasma/plasmoids/org.kde.activeWindowControl/contents/ui/main.qml:242:13: QML Text: Binding loop detected for property "computedWidth"
org.kde.plasma.pulseaudio: No object for name "alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
`
... which is a lot of mess, but it looks lie there is something going on with a few falilures when loading the widget.

**Comment by kotelnik** [comment]
Sorry for my late response: From the log says that the plugin part of the package is missing from your system - this message:
```
qml: appMenuModel failed to initialize: Error: Qt.createQmlObject(): failed to create object: 
    file:///usr/share/plasma/plasmoids/org.kde.activeWindowControl/contents/ui/inline:1:89: module "org.kde.private.activeWindowControl" is not installed
```

You need to use either plasma5-applets-active-window-control package or AUR (plasma5-applets-active-window-control-git) version or "make install" from source. If you are using store.kde.org version, you won't have AppMenu functionality.

**Comment by fkrz** [comment]
To be honest, I stopped searching for a while. But tonight I had to reinstall my system ; and I am now back to the original problem (which nicely closes that massive digression I guess - sorry about that btw).

System is the same as before, only with AntergOS instead of Manjaro. I am using the AUR package this time.

**Comment by kotelnik** [comment]
Original problem is that Application menu is not shown at all, right? I'm out of ideas right now. Just to be sure, here is what I would check to narrow the problem (I'll probably mostly repeat myself):
- make sure, there is only one installation of the widget (no KDE store version in .local/share/plasmoids)
- make sure only one AWC widget is added in plasma desktop and zero Global Menu widgets
- make sure Application Menu is actually enabled in AWC widget settings (it is off by default)
- make sure Application Menu export is enabled in Plasma settings (Settings -> Application Style -> Widget Style -> Fine Tuning -> Menubar style: Application Menu widget)
- menu only shows up for Qt5 applications
- Plasma 5.9+ is required

**Comment by kotelnik** [comment]
@giogziro95: I've made a small rework of menu buttons visual. Is your problem fixed now?

**Comment by giogziro95** [comment]
@kotelnik Sorry, but what problem are you referring to?

**Comment by giogziro95** [comment]
As I said in [this comment](https://github.com/kotelnik/plasma-applet-active-window-control/issues/61#issuecomment-290066109), the problem disappeared by itself for some reason. I kept the issue open because @fkrz also had a problem with the menu, but I think I should close it because the original problem no longer exists. If anybody else has a problem, feel free to re-open this issue or start a new one.

**Comment by noodlejetski** [comment]
I've encountered the same spacing issue, except that global menu buttons are a little bit _higher_ than the window title, as compared to the screenshot in the first post, where the menu buttons are lower than the window title.

![screenshot_20180221_122619](https://user-images.githubusercontent.com/8598559/36477749-9b36e400-1702-11e8-9932-97156bb71e36.png)

I'm running Manjaro KDE, Plasma 5.12.1, and I installed Active Window Control from AUR (`plasma5-applets-active-window-control-git`). There's no other widget displaying global menu, and I did enable global menu in AWC settings. Fill height toggle in Active Window Control Settings > Application Menu is enabled. If I disable the Fill height setting, global menu buttons drop lower than the window title, similar to the screenshot in the first post. I can't find any way to align the window title text with global menu text.

**Comment by arklee** [comment]
Same problem,even I don't know what I installed caused the problem

**Comment by Quadss** [comment]
Have the same issue on openSUSE install:

* Leap 15
* Plasma 5.12.5:
* KDE Framework version:5.45.0
* QT version 5.9.4
* Fill Height Checked 
* Installed from: "Get new widget" menu

When set to a larger bar size it works, but lowering the height messes it up to a point where it steps out of the bar (on to desktop)
