### ISSUE TITLE
Tooltip does not appear after latte dock (re-)launch

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-active-window-control#62]
If a window is on focus, the tooltip is empty after plasma restarts.

**Comment by kotelnik** [comment]
I cannot replicate this... If I'm in my Konsole and trigger plasma relaunch, then after plasma is started Konsole is still active and by moving my mouse to the widget area, tooltip is shown normally. I trigger plasma re-launch by calling this script:
```
#!/bin/bash
kbuildsycoca5
killall plasmashell
plasmashell &
```

**Comment by kupiqu** [comment]
Actually I observed that behavior in latte-dock (https://github.com/psifidotos/Latte-Dock), which is the panel I'm using. 

Could you please test if this happen in latte? I just replicated it your current master version.

**Comment by kupiqu** [comment]
I confirm this does not happen with plasma re-launch, but only in Latte Dock (my fault, I just assumed it would be the same w/o checking this out). I edited the title so it is latte dock specific.

@psifidotos, given that you are also using this applet, could you please check if this happen in your system? Thanks!

**Comment by psifidotos** [comment]
which tooltip?

**Comment by kupiqu** [comment]
It refers to the "Tooltip Text" setting in Active Window Control (see screenshot):

![image](https://cloud.githubusercontent.com/assets/3875196/25581587/bc69f526-2e56-11e7-9d3f-10429ac3fc38.png)

In my settings it is configured to show the window title. It works fine in all conditions except when the latte dock is (re-)launched. In this case the tooltip for the application under focus is empty (although moving to a different application reactivates the tooltip).

For whatever reason, this doesn't happen when AWC is embedded in a plasma panel and plasmashell is restarted. The tooltip is present for the application under focus.

**Comment by psifidotos** [comment]
I cant reproduce or I dont understand...

1. a window is active (has focus) -> tooltip is not working correctly
2. we re(launch) Latte -> the active window tooltips is not working correctly

why it should? I think that during step 2 the previous window lost the focus (neither tooltip nor the window title is shown in Active Window control)
3. by just clicking again on the previous window to gain focus then the tooltip works again

this is my behavior on my system...

**Comment by kupiqu** [comment]
Mmm, not sure we are going through the same steps. Let me describe what I exactly do to see if this is reproducible or not:

1. Let's say Konsole is under focus; now let's move the mouse to AWC (specifically to the window title or app name, not to the menu items). Expected behavior is that the tooltip for Konsole is displayed during few seconds.

2. While Konsole is under focus, let's quit from Latte (this will temporarily remove focus from Konsole, but focus will come back to Konsole once Latte is terminated).

3. Still keeping focus on Konsole, let's now use for instance Krunner to launch Latte again (once again Konsole will lose focus while in Krunner, but focus will come back to Konsole once Krunner disappears).

4. Now Latte should be present and AWC should show that Konsole is under focus.

At this point, if you repeat point 1 you would expect to see AWC tooltip for Konsole, just as before, but instead the tooltip is empty in my system.

That is basically what I referred to... I wonder if you are able to reproduce this behavior or if this is happening only in my system for whatever reason...

Thanks for helping on this!

**Comment by psifidotos** [comment]
yep... this is true...
in (3) I can write inside the konsole window but I have to either drag the konsole window or activate a different window in order for the behavior to behave correctly afterwards

The fact that the konsole name is shown correctly in AWC and its menu also it probably means that this is something inside AWC concerning the tooltip

**Comment by kupiqu** [comment]
Thanks for checking this out!

> The fact that the konsole name is shown correctly in AWC and its menu also it probably means that this is something inside AWC concerning the tooltip

That's a good point.

**Comment by kotelnik** [comment]
Can you please check if my (just pushed) last commit fixed this?

**Comment by kupiqu** [comment]
It works! Thanks to both of you for helping :)
