### ISSUE TITLE
Looks awful when there is no active window

### ISSUE THREAD

**Issue by SeptemberHX** [kotelnik/plasma-applet-active-window-control#64]
I put it on the top panel like below：
![image](https://cloud.githubusercontent.com/assets/18042424/24695478/9b69bbce-1a18-11e7-923f-45903271c1b2.png)
It looks really nice.

But when I close all windows:
![image](https://cloud.githubusercontent.com/assets/18042424/24695527/bf420484-1a18-11e7-93f2-a20b13c3cd68.png)

Maybe it's hard to set it's size flexiable. Could you please just let it show some text on it like this ?
![image](https://cloud.githubusercontent.com/assets/18042424/24695656/2ec10792-1a19-11e7-90f9-414e01b429bf.png)

And an option to choose showing whether buttons/window Tiles or UserName when current window is not maximized would be nice.

**Comment by trmdi** [comment]
Your issue is similar to mine: https://github.com/kotelnik/plasma-applet-active-window-control/issues/63

**Comment by SeptemberHX** [comment]
Ohh, I found fleiable size in settings

But I still want it to show username ... It feels strange when changing size.

**Comment by SeptemberHX** [comment]
Never mind this. I updated it to the newest version, and everything goes well

**Comment by kotelnik** [comment]
So I came too late after the "party", sorry :). Feel free to open this issue when necessary.
