### ISSUE TITLE
Appearance Improvements

### ISSUE THREAD

**Issue by psifidotos** [kotelnik/plasma-applet-active-window-control#65]
I have adjusted some improvements in appearance in my system, would you accept  any if I make a PR?

![image](https://cloud.githubusercontent.com/assets/2216474/24933491/4a03270a-1f1f-11e7-9fa4-c8382b4a6585.png)

![image](https://cloud.githubusercontent.com/assets/2216474/24933502/5a701cf6-1f1f-11e7-90e1-3c6e6912682e.png)

**Comment by kotelnik** [comment]
Sorry for my late responses. As I said in your pulls, thanks a lot for your inputs! And if something is missing, let me know :).

**Comment by kotelnik** [comment]
I'm closing this, I believe we discus these changes elsewhere. If not, reopen please :).
