### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by Wuxiangdong** [kotelnik/plasma-applet-active-window-control#7]
Though I disable showing buttons,buttons are still showed.
![19](https://cloud.githubusercontent.com/assets/7942339/9158913/5fc08e7a-3f51-11e5-82db-1b2a0141a395.png)

**Comment by Wuxiangdong** [comment]
But if I disable "Do not hide on mouse out",Buttons will disapper

**Comment by kotelnik** [comment]
Thanks, nice bug discover! I'll fix it.

**Comment by kotelnik** [comment]
Should be fixed now, thanks again!

**Comment by Wuxiangdong** [comment]
Thank :>
