### ISSUE TITLE
Invisible buttons in optons

### ISSUE THREAD

**Issue by michaldybczak** [kotelnik/plasma-applet-active-window-control#70]
My screenshot says it all:

https://puu.sh/vsBPC/22d669dce0.png

At the moment I do customization blindly, moving buttons, saving and checking on a window if that's what I want. There are only a few buttons so it works, but is a bit uncomfortable.

Buttons looked that way no matter from which source I had the widget (kde-store, manjaro repo or AUR).

**Comment by kotelnik** [comment]
Thanks! Should now be fixed. Please reopen if the problem is still there.

**Comment by michaldybczak** [comment]
There was no AUR update of your package so nothing has changed.

r95.8453d6e-1
Build date: sob. - 22/04/2017 16:53:10

Will be waiting for update, thanks :)

**Comment by kotelnik** [comment]
It is now updated, thanks for reminding me. Actually there is no need to bump the version of -git AUR packages. You can simply reinstall them and latest master is pulled automatically. Some package maintainers don't bump versions, some does. There is unfortunately no unified opinion about this. So I do this sometimes... :)

**Comment by michaldybczak** [comment]
Awesome!
I rely on system update messages. If it doesn't show me anything new, why would I update something that seems to be the same? Version update matters a lot. I'm currently installing a new version and will let you know how it works. Thanks!

**Comment by michaldybczak** [comment]
It works! Thanks, love it!

**Comment by michaldybczak** [comment]
Uh, it's even worse than before, because even X button became invisible...

https://puu.sh/vFp2y/ccf04610d9.png

Still, I was happy with the latest update, because of aurorae themes support! I can wait for the button visibility improvements. I might also add that this bug was present in all versions (AUR, Manjaro repo, kde-store).

**Comment by kotelnik** [comment]
Sorry, my bad. Please try now.

**Comment by michaldybczak** [comment]
It works now! :D. Thanks!
https://puu.sh/vFu91/b3b56b3097.png
