### ISSUE TITLE
Visual improvements - part 2

### ISSUE THREAD

**Issue by psifidotos** [kotelnik/plasma-applet-active-window-control#73]
@@@ **_commenting the previous merge of changes_** @@@

@kotelnik thank you very much for considering the changes!! :)

I am using the master branch and I am satisified.
I would like your opinion on the following (this is what I miss) :

1. When the window title is appearing with its menu, I prefer the window title to become **bold**, it is an easy way to distinguish the title from the menu
2. You kept the top alignment for the menu bar (instead of the bottom one) but even this way it is very difficult to just use the menu font scaling in order to achieve, **same font size with the window title and correct vertical alignment with it**
3. I like that you kept the separator line between the window title and the menu bar. The only small issue I have is that in order to be in the center of the distance between title and menubar needs a very big menu side margin. I think that the separator line should be always in the center of the distance of window title and menu (this is not possible for menu side margin lower than 20px. in my system)
4. the previous layout of the separator was exactly the one used by the audoban's separator (which is the only separator plasmoid available :) ).  On the screenshot below you can observe that the active window separator is distinguished from all other panel's separators... If I remember correctly,
the audoban's separator uses:
- always a top and bottom margin of 4px. and left and right of 3px in horizontal panels.
(this is why is used 2*4 and 2*3 in the previous commit)
- opacity at 0.5

thanks a lot for this fantastic plasmoid and I am considering it one the biggest community contributions in kde !!! :)

![image](https://cloud.githubusercontent.com/assets/2216474/25303574/a4424628-275e-11e7-82e9-7a429dc1b482.png)

**Comment by kotelnik** [comment]
Sorry, I missed this one. I just replied in the other conversation :).

**Comment by kotelnik** [comment]
Reopen if necessary.
