### ISSUE TITLE
Does not support aurorae decoration themes with .svgz files

### ISSUE THREAD

**Issue by kennethso168** [kotelnik/plasma-applet-active-window-control#76]
Hi, I had a look of 119446a.
I found that the file extensions of the custom theme are hardcoded to ".svg"
```
property string buttonImagePath: customAuroraeThemePath ? customAuroraeThemePath + '/' + 
iconName + '.svg' : Qt.resolvedUrl('../icons/' + themeName + '/' + iconName + '.svg')
```
This will make it not work on themes with .svgz files, like [Arc KDE](https://github.com/PapirusDevelopmentTeam/arc-kde/tree/master/aurorae/themes/Arc)

I also tried with the latest version with Arc Dark theme. The window controls are missing. But the buttons are shown correctly if I rename all *.svgz files in the aurorae theme manually to *.svg. Thank you.

**Comment by kotelnik** [comment]
It should now be supported - I've added a selectbox for the extension (in settings). This was the simplest way for now. Eventually I'd like to implement more convenient way of selecting a theme...

**Comment by kotelnik** [comment]
Oh and thanks for reporting! Please reopen this if the problem persists.
