### ISSUE TITLE
Not showing the window buttons in panel if using other themes than breeze 

### ISSUE THREAD

**Issue by jlda** [kotelnik/plasma-applet-active-window-control#79]
### I am using Latte Dock for my panel and after my system start or after I restart Latte the buttons are not showing. I have to select in the aurorae themes selection .svgz and apply and then select the .svg again to show the buttons on the panel

![spectacle x21216](https://cloud.githubusercontent.com/assets/11981120/26288911/688200ee-3e68-11e7-8f05-631478a5c458.png)

**Comment by kotelnik** [comment]
It should now be fixed in git master. Please reopen if problems occur. Thanks!
