### ISSUE TITLE
Report another bug..

### ISSUE THREAD

**Issue by Wuxiangdong** [kotelnik/plasma-applet-active-window-control#8]
Today when I look up a theme for kde5.I find a bug.
![26](https://cloud.githubusercontent.com/assets/7942339/9376501/79438fea-4740-11e5-8132-64bc9a6ec098.png)
![27](https://cloud.githubusercontent.com/assets/7942339/9376505/8669f0e2-4740-11e5-94e7-9cd4d0ffb3e9.png)

There are the same bug in buttons.

**Comment by Wuxiangdong** [comment]
The applet doesn't control the active window but the parent (Perhaps it should be the word )window

**Comment by kotelnik** [comment]
Hi! I think the non-controlled window is more like "modal dialog" and these dialogs are part of their parent window. But I agree they should be controllable by the widget. I try to investigate why this is not happening and try to fix it. Thanks for reporting!

**Comment by Wuxiangdong** [comment]
Thanks for your project and help:)

**Comment by kotelnik** [comment]
Hi! Unfortunately I was unable to fix this issue. For now I am cannot close modal dialog of a window from QML code. I've looked inside taskmanager and windowlist widgets code and none of them can do such thing. You can for example try to close a modal dialog from "Icon Only Task Manager" widget - it cannot be done. When this taskmanager is able to control modal dialogs, my widget will be able to do that as well.

**Comment by Wuxiangdong** [comment]
Ok.Anyway,it is a good applet:)

**Comment by Wuxiangdong** [comment]
It is fixed after updating plasma 5.7
:)
