### ISSUE TITLE
After update to plasma 5.10, AWC makes plasma (or latte-dock) crash

### ISSUE THREAD

**Issue by kupiqu** [kotelnik/plasma-applet-active-window-control#84]
I first thought it was a Latte-dock issue, but it turned out it was AWC.

Please see https://github.com/psifidotos/Latte-Dock/issues/507

**Comment by cuentawarra** [comment]
its awc , i dont use latte dock and after update desktop was crashing , had to manually remove the plasmoid

**Comment by fedor1113** [comment]
Definitely. The same problem. Any ideas on how to fix the issue?

**Comment by kotelnik** [comment]
I'm working on it.. :)

**Comment by kotelnik** [comment]
Mostly fixed. Please test.

Known issue: if "show active window only for plasmoid's screen" is checked and you move your active window outside of the plasmoid's screen, it will stay active in the plasmoid until active task is changed.

**Comment by kupiqu** [comment]
It works!

One (minor) thing that seems to not work now though is that buttons appear all the time irrespective of the setting: show only when maximized.

Could you check? Should I open a different issue?

**Comment by fedor1113** [comment]
True. It is reproducible. I have the same issue. I was actually going to open it, but you can do it.

**Comment by fedor1113** [comment]
Haven't looked at the code, but tried to tweak the applet's settings in different ways - the option does not work at all.

**Comment by fedor1113** [comment]
IMHO, the original issue here is completely gone. I think it can be closed.

**Comment by kupiqu** [comment]
I agree, and issue #85 has already been opened

**Comment by libookami** [comment]
Hi, it still crashes for me. This is what i get if i execute plasmashell from the CLI:

KCrash: Attempting to start /usr/bin/plasmashell from kdeinit
sock_file=/run/user/1000/kdeinit5__0
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = plasmashell path = /usr/bin pid = 9760
KCrash: Arguments: /usr/bin/plasmashell 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__0
QSocketNotifier: Invalid socket 8 and type 'Read', disabling...
QSocketNotifier: Invalid socket 37 and type 'Read', disabling...
QSocketNotifier: Invalid socket 9 and type 'Read', disabling...

**Comment by kotelnik** [comment]
> it still crashes for me.
This is weird. Please make sure you don't have kde-store version installed at the same time. Next, please try to test with empty plasma config so there is stock configuration of plasma panel and AWC (after added to panel).

**Comment by kotelnik** [comment]
@kupiqu and others: Thanks for reporting this! :)

**Comment by libookami** [comment]
Thanks a lot, it worked!. This is what i did in case someone else has the same problem:
- Delete plasma's configuration in ~/.config
- Delete anything in ~/.local/share/plasma/
Yes, i had a version of this plasmoid from the store in ~/.local/share/plasma/plasmoids/ Most probably that was the problem but because i played safe and deleted everything in ~/.local/share/plasma/ i didn't check if that was the only problem.
