### ISSUE TITLE
"Show only when maximized" option is ignored in Plasma 5.10

### ISSUE THREAD

**Issue by Void97** [kotelnik/plasma-applet-active-window-control#85]
Hi, after today's update for KDE Plasma 5.10 compatibility, the option "show only when maximized" is ignored. In fact, the window buttons are always visible, even if the current window is not maximized.

**Comment by kotelnik** [comment]
Thanks for reporting! It should now be fixed along with the previously mentioned known issue (https://github.com/kotelnik/plasma-applet-active-window-control/issues/84#issuecomment-305105918).

Please reopen if problems occur.

**Comment by kupiqu** [comment]
It works great, thanks!

**Comment by fedor1113** [comment]
Perfect again! Love that applet. Thank you.
