### ISSUE TITLE
Mouse wheel up broke on Plasma 5.10

### ISSUE THREAD

**Issue by andrevmatos** [kotelnik/plasma-applet-active-window-control#86]
In the line of the other issues with freshly launched Plasma 5.10, mouse wheel **up** over AWC has no action, despite `Mouse wheel up to maximize` checked on plasmoid settings.

Also, mouse wheel down set to unmaximize keeps toggling maximized/unmaximized states, making it diverge from kwin's behavior, where if mouse wheel is set to maximize/unmaximize, mouse wheel down only unmaximize, and mouse wheel up only maximize, avoiding keeping toggling between states, as mouse wheel can be a little hard to perform only one 'wheel up' or down.

**Comment by kotelnik** [comment]
Hi, thanks for reporting! I believe this issue is related to this one: https://github.com/kotelnik/plasma-applet-active-window-control/issues/85. It should now be fixed in git master. Please test if it is working for you now. Reopen if necessary.

**Comment by andrevmatos** [comment]
Yes, working flawlessly on r122. Thank you for this awesome addition to plasma community!

**Comment by kotelnik** [comment]
Thanks! I'm glad you like it :).
