### ISSUE TITLE
Incomplete Russian Translation

### ISSUE THREAD

**Issue by Jacobtey** [kotelnik/plasma-applet-active-window-control#87]
It's very strange, but the section Application Menu and "Toggle pin to all Desktops" are not translated. But if the .po is manually converted to the .mo, then everything is fine.

**Comment by kotelnik** [comment]
Thanks for reporting! I didn't know that before but apparently the keyword "fuzzy" was preventing such translations to be used. I've removed that and it is working now.

**Comment by Jacobtey** [comment]
ok. it works properly now. thanx
