### ISSUE TITLE
Does not work with Plasma 5.8 anymore

### ISSUE THREAD

**Issue by Vogtinator** [kotelnik/plasma-applet-active-window-control#88]
Plasma 5.8 is an LTS release and still supported by KDE and many distros.
However, since the 5.10 support commits this does not work anymore with Plasma 5.8.

**Comment by kotelnik** [comment]
I'll set up neon LTS docker and get to it :).

**Comment by kotelnik** [comment]
I believe it is now fixed in git master. Please confirm if possible.

**Comment by Vogtinator** [comment]
Yes, that works. Thanks!
