### ISSUE TITLE
Window is closed when icon is clicked on the upper left

### ISSUE THREAD

**Issue by joseffilzmaier** [kotelnik/plasma-applet-active-window-control#9]
Hey there, me again :) !

I have been using your applet for a while now and its super-awesome!
I just recently discovered a bug, though: I have disabled "control buttons" and the buttons do not show up. However, if i click on the top left on the applet it closes the window, as if the "control buttons" were enabled. So i occationally close my windows if i just want to trigger the present windows effect.

It is not always the top left, it is tied with the selection of the button position, in my case "uppler left" is selected (although control buttons are disabled)

It's just a minor annoyance and my workaround is to set the button size to as small as possible, so i close the windows a lot less by accident.

Thanks in advance!

**Comment by kotelnik** [comment]
Hi! Good bug-catch, thanks! Should be fixed now.

**Comment by joseffilzmaier** [comment]
Thanks for the immediate fix :D 
This issue can be closed.

**Comment by kotelnik** [comment]
This one was easy and I had time so it was a lucky coincidence :) I'm usually not that fast, unfortunately :)
