### ISSUE TITLE
Maximize button stays in hovered state after maximizing window

### ISSUE THREAD

**Issue by marhkb** [kotelnik/plasma-applet-active-window-control#91]
"Remove window decarations" is enabled. Wenn I click the maximize button on a maximized window and after that maximize the window again the button renders itself as it where hovered with the mouse.

I have made a video
[hovered.zip](https://github.com/kotelnik/plasma-applet-active-window-control/files/1066393/hovered.zip)

**Comment by fliperama00** [comment]
Same here. Compiled from source
