### ISSUE TITLE
[Feature Request] - Show Activity Name

### ISSUE THREAD

**Issue by psifidotos** [kotelnik/plasma-applet-active-window-control#95]
Currently AWC supports showing for the plasma desktop either the text **Plasma Desktop** or a text that the user has specified from the settings. 
I think it would be much more informative if **instead** the name of the current Activity was shown

**Comment by kupiqu** [comment]
That sounds like a good idea to me

**Comment by psifidotos** [comment]
pretty meaningful... :)

![image](https://user-images.githubusercontent.com/2216474/27729795-be59df78-5d8f-11e7-9624-6e310c0f408c.png)

![image](https://user-images.githubusercontent.com/2216474/27729823-d41fbbca-5d8f-11e7-9f74-9722b1e52055.png)

**Comment by kupiqu** [comment]
Somehow it doesn't work for me, the applet doesn't launch :/

**Comment by psifidotos** [comment]
plasma version? any errors?

**Comment by kupiqu** [comment]
Ok, it's fixed. Most absurd issue. There was a character issue after copying manually from github...

The thing is I didn't have right access to apply your patch and not being very proficient in git (didn't know how to apply your commit into my local branch), and given that there were only few changes in your commit I decided to apply them manually... and that was the result, my bad!

**Comment by kupiqu** [comment]
It's nice to have activity name in AWC, btw! :)

**Comment by psifidotos** [comment]
yeah... I use it also!!! It very easy and clean now to identify in which activity I am working on

**Comment by kupiqu** [comment]
Now that we have the activity name, extra points would be to have the option to move from one activity to another via a right click option... Would that make sense?

**Comment by kupiqu** [comment]
Currently it shows 'close', 'maximize', 'minimize', etc. These are windows options that do not apply when focus is on desktop. The option to switch activities would be more proper, I think...

**Comment by psifidotos** [comment]
this commit hasnt merged yet...

**Comment by kupiqu** [comment]
yeah, let's wait to see what @kotelnik thinks about all this... :)

**Comment by kotelnik** [comment]
Sorry, @kotelnik is on vacation and finally got to the internet :))). First, sorry for my late responses. 

Thanks for the suggestions. I've just merged the @psifidotos pull (THANKS!) with some additional changes (I'm proposing %activity% placeholder instead of the checkbox). I think this is more flexible for the user... I hope it's ok for you?

As for the activity switching, I agree it should be added as a feature. Dropdown menu makes sence, @kubiqu, thanks for the suggestion! I'll look into it.

**Comment by kotelnik** [comment]
Please try latest commits for activity switching by standard right-click dropdown menu. Criticism appreciated :).

**Comment by kupiqu** [comment]
It works just great!
